<div class="book-heading" style="padding:3vw 0; background-image: url(http://cuentos.dev/public/img/bookbg.jpg);background-position: center;
    background-size: 100%;
    background-repeat: no-repeat;">
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title" style="color:white">Términos y condiciones</h1>
    </div>
</div>
<style>
    .mb20 {
        margin-bottom: 20px;
    }

    .overlay {
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
        background: rgba(0, 0, 0, .3);
    }

    .contact ul li a {
        padding: 10px;
        display: block;
        color: #29abe2;
    }

    .social-contact {
        list-style: none
    }

    .social-contact li {
        border-bottom: 0px !important;
        list-style: none;
        display: inline-block;
        margin: 2px 5px;
    }

    .social-contact li a {
        text-decoration: none !important;
        border: 1px dashed #29abe2;
        height: 40px;
        width: 40px;
        text-align: center;
        line-height: 1.3em;
        color: #29abe2;
        font-size: 16px;
        border-radius: 100%;
    }

    .social-contact li a:hover {
        color: #333;
    }

    .team-member {
        font-family: 'Gloria Hallelujah';
        color: #29abe2;
        text-align: center;
        font-size: 43Px;
    }

    .nombre {
        font-family: 'Gloria Hallelujah';
        color: #29abe2;
        text-align: center;
        font-size: 43Px;
    }

    .puesto {

        font-family: "Gloria Hallelujah";
        font-size: 20px;
        color: #333;
    }

    .descripcion {
        margin-top: 20px;
    }

</style>
<section class="section section-home">
    <div class="container">
        <link href="https://fonts.googleapis.com/css?family=Stalemate" rel="stylesheet">

        <div class="row contact">
            <div class="col-sm-12">
                <p>
                    MI CUENTO MAGICO crea cuentos para niños a través de un avatar configurable por usted mismo para que
                    se parezca lo máximo posible al protagonista de cada historia acompañado de su nombre, también
                    personalizable. Cada libro se realiza bajo pedido, para adaptarse al personaje con infinita
                    combinatoria y el nombre único de cada niño. Esta página está operada y es propiedad de Gloria María
                    Vélez Bermúdez. Si desea contactarnos en relación a cualquier contenido de la página, no dude en
                    contactar con nosotros a través de nuestro formulario.
                    <br />
                    <br />
                    Estos términos y condiciones regulan los contenidos y el uso de la página www.micuentomagico.com (la
                    “página”) y establecen los términos y condiciones bajo los que suministramos los productos
                    disponibles en la página (los “productos”). Por favor, lea cuidadosamente estos términos y
                    condiciones de venta antes de utilizar la página y antes de realizar el pedido de productos a través
                    de ella. Al usar esta página y/o realizar un pedido de productos, usted debe indicar que ha leído y
                    entendido los términos y condiciones generales, y que está de acuerdo con ellos. Puede imprimir una
                    copia de estos términos y condiciones haciendo click en el icono de imprimir de su explorador.
                    <br />
                    <br />
                    Estos términos y condiciones se aplicarán a todas las ventas que realicemos a través de la página y
                    sustituirán a otros términos o condiciones con referencia a otro lugar, mencionado o implícito por o
                    en el comercio, costumbre, práctica o curso de las negociaciones a menos que se ponga por escrito en
                    contacto con nosotros. Si no está de acuerdo con estos términos y condiciones, no debería usar la
                    página. Por favor, tenga en cuenta que podemos modificar estos términos y condiciones, por lo que
                    deberá revisarlos periódicamente. Si usted continúa usando la página se estimará que acepta dichos
                    cambios.
                </p>
                <br />
                <br />
                <h3>Definiciones</h3>
                <p>
                    "Comprador" hace referencia a la persona mencionada en el pedido;
                    <br />
                    <br />
                    "Contrato" hace referencia al pedido y a la confirmación del pedido;
                    <br />
                    <br />
                    "Daños" hace referencia a daño o desperfectos;
                    <br />
                    <br />
                    "Pedido" hace referencia a su pedido de un producto de la página;
                    <br />
                    <br />
                    "Precio" hace referencia al importe total en el momento del pedido, incluyendo los gastos de envío y
                    empaquetado, y otras tasas aplicables, sujeto a cualquier oferta promocional o descuento aplicable;
                    <br />
                    <br />
                    "Términos y condiciones" hace referencia a las condiciones en este documento.
                </p>
                <br />
                <br />
                <h3>Acceso a la Página y su uso</h3>
                <p> Usted no puede hacer uso de la página de ninguna forma ilegal o inapropiada, quebrantando ninguna
                    legislación o permiso aplicable a usted. Usted acepta seguir todas las instrucciones que ofrezcamos
                    en relación al uso de la página.
                    <br />
                    <br />
                    Tras realizar su pedido, usted acepta que revisemos su pedido y el contenido de éste conforme a
                    nuestras directrices y en cumplimiento de nuestros términos y condiciones, y que tenemos la potestad
                    de rechazar el procesamiento de cualquier pedido que consideremos que incurre en una violación de
                    nuestras directrices y dichos términos y condiciones.
                </p>
                <br />
                <br /><h3>Derechos de Propiedad y Uso</h3>
                <p> Todos los derechos de propiedad (incluyendo patentes, marcas registradas y no registradas y marcas
                    de servicio, nombres de dominio, diseños registrados y derechos de diseño, derechos de autor,
                    derechos de bases de datos, derechos morales y derechos de programas informáticos) incluidos en la
                    página, y todo el contenido y materiales de la página (“contenido de la página”) son propiedad
                    nuestra, y deben seguir siendo propiedad nuestra o de nuestros licenciatarios. El contenido del
                    sitio solo puede usarse para fines personales no comerciales, y no puede ser reproducido,
                    modificado, copiado, alterado, distribuido, republicado, mostrado, transmitido o vendido de ninguna
                    forma, por ningún medio, total o parcialmente. Usted no puede retirar ninguna advertencia de
                    propiedad o derechos de autor de ningún contenido de la página.
                </p>
                <br />
                <br /> <h3>Pedidos y Especificaciones</h3>
                <p> Todos los productos en venta están sujetos a disponibilidad y a nuestra aceptación de su pedido.
                    <br />
                    <br />
                    Nos reservamos el derecho a rechazar cualquier pedido sin la obligación de aportar ningún motivo
                    para dicho rechazo. Ningún pedido deberá considerarse aceptado por nosotros hasta que lo hayamos
                    confirmado a través de la confirmación de pedido.
                    <br />
                    <br />
                    Es su responsabilidad contactar con nosotros y notificarnos de cualquier error con el pedido lo
                    antes posible. El no hacerlo puede conllevar un procesamiento erróneo del pedido.
                    <br />
                    <br />
                    Nos esforzamos por mostrar y describir de la forma más precisa los colores impresos del producto que
                    mostramos en nuestra página, pero no podemos asegurar que los colores del producto entregado
                    coincidan con aquellos mostrados en su monitor o en la pantalla de su teléfono móvil.
                </p>
                <br />
                <br /> <h3>Precio, pago y Moneda</h3>
                <p> Todos los precios incluyen IVA. El pago se efectúa a través de la plataforma de pago de Paypal, TPV
                    y/o transferencia bancaria al momento de realizar su pedido y que éste sea aprobado por nosotros. En
                    ese momento, se realizará un cobro íntegro y el contrato entrará en vigor.
                    <br />
                    <br />
                    Usted se compromete a que todos los detalles que nos proporcione con el fin de llevar a cabo la
                    entrega de su pedido sean correctos, y que el método de pago escogido sea de su propiedad y en éste
                    existan fondos suficientes o posibilidades crediticias para cubrir el coste total del pedido.
                </p>
                <br />
                <br /><h3 id="envios">Entrega</h3>
                <p> El lugar de entrega de nuestros productos se mostrará en el pedido, y el método normal de entrega
                    (salvo que se especifique y acuerde un método distinto).
                    <br />
                    <br />
                    Nos esforzaremos para procesar y gestionar su pedido en el tiempo establecido para cada artículo.
                    Sin embargo, los tiempos de fabricación pueden variar en ocasiones, por lo que los plazos de entrega
                    de los productos son indicativos. El tiempo de entrega no debe constituir la esencia de estos
                    términos y condiciones y no nos haremos responsables de pérdidas o gastos que pueda sufrir como
                    resultado de un retraso en la entrega de su pedido.
                    <br />
                    <br />
                    Usted deberá revisar su producto tras su entrega y, en caso de que el producto haya sido entregado
                    por un transportista, firmar el documento de aceptación del paquete. Una firma en el documento de
                    entrega constituirá evidencia de que usted ha recibido el pedido sin daños ni defectos aparentes.
                    Usted no podrá rechazar el pedido o parte de éste únicamente a base a una entrega realizada con
                    retraso en un pedido que consiste en varias entregas. Si en el momento de la entrega los productos
                    se muestran defectuosos o dañados, usted deberá proporcionar una descripción por escrito de los
                    daños o defectos, firmado por usted.
                    <br />
                    <br />
                    Nos reservamos el derecho a hacerle llegar su pedido en distintas entregas. En caso de que su pedido
                    esté programado para realizarse en distintas entregas, cada entrega constituirá un contrato
                    independiente.

                    Si por error no recoge el pedido, entonces bajo ninguna obligación le reembolsaremos el precio.
                </p>
                <br />
                <br /><h3>Riesgo y propiedad</h3>
                <p> Una vez entregada el pedido a la dirección acordada, el riesgo de daños o pérdida pasará a Usted. La
                    propiedad pasa a Usted solo en el momento en que nosotros recibamos el importe total del precio
                    acordado.
                </p>
                <br />
                <br /><h3>Devoluciones, reembolsos y derechos de cancelación</h3>
                <p> Usted tiene derecho a cancelar un pedido sólo en las siguientes circunstancias:
                    <br />
                    <br />
                    Si no hemos podido entregar el pedido en un periodo de 40 días tras la fecha del pedido.
                    En el caso de productos defectuosos, tan pronto como haya descubierto el defecto (teniendo en cuenta
                    que haya inspeccionado el producto tan pronto como haya sido posible tras la entrega y, en ningún
                    caso, más allá de 14 días tras la recepción del producto).
                    Si se cancela un pedido bajo las condiciones a o b, nosotros nos haremos responsables de todos los
                    costes (incluyendo cargos iniciales de entrega y re-entrega (en caso de haberlos) del pedido en
                    cuestión.
                    <br />
                    <br />
                    Las notificaciones que impliquen un deseo de cancelación deben enviarse usando el formulario de
                    contacto
                    <br />
                    <br />
                    Salvo productos dañados, nada en estos términos y condiciones debe darle derechos de cancelación en
                    relación a dichos productos que, por su naturaleza, han sido hechos a su medida y son claramente
                    personalizados.
                    <br />
                    <br />
                    Usted deberá devolvernos cualquier producto en su embalaje original (que deberá conservar para dicho
                    propósito).
                    <br />
                    <br />
                    Nada de lo incluido en esta cláusula afecta a sus derechos estatutarios.
                </p>
                <br />
                <br />
                <h3>Aviso de responsabilidad</h3>
                <p> A pesar de que nos esforzamos para asegurar que la información contenida en la página (contenido de
                    la página), es correcta y está libre de errores, no podemos garantizar la exactitud del contenido de
                    la página. Es posible que realicemos cambios en el contenido de la página o en algunos productos,
                    precios o tarifas descritas en ellos, en cualquier momento y sin previo aviso. El contenido de la
                    página puede estar obsoleto, y no nos comprometemos a actualizar dicho material.
                    <br />
                    <br />
                    Parte del contenido de la página puede ser ofrecido por terceros, y no garantizamos ni aceptamos
                    ningún tipo de responsabilidad por su exactitud, actualidad o fiabilidad.
                    <br />
                    <br />
                    Salvo puesto explícitamente en estos términos y condiciones, el sitio y todo el contenido del sitio
                    proporcionada a través de él se proporcionan "tal cual" y sin representación o garantía de ningún
                    tipo, ya sea expresa o implícita (ya sea por el derecho común, de encargo, ley o de otro modo). En
                    la máxima medida permitida por la ley aplicable, negamos todas las condiciones de otros,
                    representaciones, declaraciones y garantías (incluyendo, pero no limitado a, cualquier garantía
                    implícita de la aptitud para un propósito particular del sitio o el contenido del sitio o que su uso
                    del sitio o el contenido del sitio no infringirá los derechos de terceros).
                    <br />
                    <br />
                    No garantizamos que la página, cualquier contenido de la página y cualquier función de la página
                    estén libres de errores, que dichos errores serán corregidos o que la página o el servidor que la
                    sostiene esté libre de virus u otros componentes dañinos. No garantizamos que la página y sus
                    contenidos cumplan con sus requisitos ni garantizamos los resultados del uso de cualquier contenido
                    de la página en términos de exactitud, actualidad, fiabilidad u otros. No nos hacemos responsables
                    de la seguridad de la página o de cualquier alteración o pérdida que la página pueda causar. Del
                    mismo modo, no nos hacemos responsables de la pérdida o daño de cualquier material en tránsito, o de
                    la pérdida o daño de materiales o datos al descargar en cualquier equipo informático.
                </p>
                <br />
                <br /> <h3>Responsabilidad</h3>
                <p> Le garantizamos que cualquier producto comprado a través de nuestra página goza de una calidad
                    satisfactoria y está orientado a los fines que se le atribuyen. En la máxima medida permitida por la
                    ley aplicable, negamos todas las condiciones de otros, representaciones, declaraciones y garantías,
                    ya sean expresas o implícitas (ya sea por la ley común, la costumbre, la ley o de otro modo).
                    <br />
                    <br />
                    Nuestra responsabilidad por las pérdidas que usted pueda sufrir como consecuencia de la violación de
                    este contrato, está estrictamente limitada al precio neto de compra del producto (excluyendo tasas y
                    gastos de envío).
                    <br />
                    <br />
                    Nada de los incluido en estos términos y condiciones excluye o limita nuestra responsabilidad en:
                    muertes o daños personales causados por nuestra negligencia u otras pérdidas resultado de su
                    confianza en cualquier tergiversación hecha por nosotros; o cualquier responsabilidad que no pueda
                    ser excluida o limitada bajo la ley aplicable.
                    <br />
                    <br />
                    Usted acepta que su navegación por la página, y su uso de esta, así como el uso del contenido del
                    sitio, se efectúan bajo su propia responsabilidad y riesgo.
                    <br />
                    <br />
                    En relación a lo anterior, usted accede a que no nos hagamos responsables de: (a) ninguna pérdida o
                    daño directo; (b) ninguna pérdida o daño indirecto o ningún daño punitivo, incidental o
                    consecuencial de ningún tipo que no esté asociado con el incidente que causa su reclamación; o (c)
                    ninguna pérdida de beneficios o ahorros o pérdida o corrupción de datos (en cada caso, sean directos
                    o indirectos) , y esto en cada caso, ya sea basado en contrato, agravio (incluyendo negligencia),
                    responsabilidad estricta o de otro modo, que surja de o esté relacionado de cualquier manera con (i)
                    el uso de este Sitio o el Contenido del Sitio; (ii) estos Términos y Condiciones (iii) los productos
                    (iv) cualquier fallo o retraso en el uso de cualquier componente del Sitio, el Contenido del Sitio o
                    cualquier servicio, incluyendo, sin limitación, la no disponibilidad del Sitio, el Contenido del
                    Sitio o de los servicios, independientemente de la duración de cualquier período de no
                    disponibilidad; (v) cualquier uso o dependencia de cualquier contenido del sitio o de cualquier otra
                    información, material, software, productos, servicios y gráficos relacionados obtenidos a través del
                    Sitio, en todos los casos, incluso si hemos sido advertidos de la posibilidad de tal pérdida o daño.
                    <br />
                    <br />
                    No nos hacemos responsables de cualquier pérdida, daño, o gastos (incluyendo pérdida de ganancias)
                    que surjan directa o indirectamente de cualquier fallo o retraso en la ejecución de cualquier
                    obligación en virtud de estos Términos y Condiciones, por causa de algún evento o circunstancia
                    fuera de nuestro control razonable, incluyendo, pero no limitado a, huelgas, acciones industriales,
                    fallo de fuentes de alimentación o equipos, acciones del gobierno o fenómenos naturales.
                    <br />
                    <br />
                    Las leyes aplicables en su país de residencia pueden no permitir la limitación o exclusión de
                    responsabilidad por daños incidentales o consecuenciales, por lo que la limitación o exclusión
                    anterior puede no aplicarse en su caso.
                    <br />
                    <br />
                    Debido a los riesgos inherentes de la utilización de Internet, no podemos hacernos responsables de
                    cualquier daño o virus que pueda infectar su equipo informático o cualquier otro bien cuando utilice
                    o navegue por la página. La descarga u otra adquisición de cualquier contenido de la página a través
                    de la página se realiza bajo su propio criterio y riesgo y con la aceptación de que usted será el
                    único responsable de cualquier daño a su sistema informático o pérdida de datos que resulte de la
                    descarga o adquisición de cualquier contenido del sitio.
                </p>
                <br />
                <br /><h3>Indemnidad</h3>
                <p> Usted se compromete a indemnizar, mantener indemne, defender y mantener a nosotros y nuestras
                    compañías matrices, subsidiarias, afiliadas y cada uno de nuestros respectivos funcionarios,
                    directores, empleados, propietarios, agentes, contratistas, socios, proveedores de información y
                    licenciatarios de y contra cualquier tipo de reclamos, daños, responsabilidad, demandas, pérdidas,
                    costos y gastos (incluyendo honorarios legales) (sea o no previsible o evitable) incurridos o
                    sufridos por cualquiera de esas partes y cualquier reclamación o procedimiento judicial que se
                    llevaron o amenazadas que surja de o en conexión con su uso del sitio, el contenido del sitio o los
                    servicios prestados a través del sitio, su conducta en relación con el sitio o los servicios
                    prestados o con otros usuarios del sitio, cualquier compra, transacciones, acuerdos o arreglos con
                    terceros a través del Sitio o en un sitio de terceros, o cualquier violación de estas Condiciones
                    generales de Uso o de cualquier ley o los derechos de terceros.
                </p>
                <br />
                <br /><h3>Terminación</h3>
                <p> Podemos eliminar la página o cesar la prestación de cualquiera de los servicios disponibles a través
                    de la página en cualquier momento a nuestro único criterio, por cualquier razón que sea.

                    Podemos interrumpir el acceso a la página por cualquier motivo bajo nuestro único criterio, en
                    cualquier momento con o sin previo aviso.
                </p>
                <br />
                <br /> <h3>Protección de Datos y Privacidad</h3>
                <p>Sólo utilizaremos la información personal que podemos recopilar sobre usted de acuerdo con nuestra
                    política de privacidad. Esta política forma parte esencial de estos términos y condiciones, por lo
                    que es importante que la lea. Al aceptar estos términos y condiciones usted también acepta y da su
                    consentimiento a nuestra política de privacidad.
                </p>
                <br />
                <br />
                <h3>Ley aplicable</h3>
                <p>Este acuerdo se efectuará con arreglo a las leyes de España y sujeto a la jurisdicción de los
                    tribunales españoles.
                </p>
                <br />
                <br />
                <h3>Realización de un pedido</h3>
                <p>Para realizar un pedido usted deberá seguir el procedimiento de pedido que figura en la página. Los
                    detalles del precio a pagar para cualquier producto, así como el procedimiento de pago se muestran
                    en la página.
                    <br />
                    <br />

                    Cualquier plazo de tiempo o fecha establecida para la entrega es solo una estimación. Nos
                    esforzaremos para entregar su pedido dentro del tiempo especificado, pero no aceptaremos
                    responsabilidad por cualquier fallo en la entrega dentro del periodo especificado.
                    <br />
                    <br />

                    Al realizar un pedido a través de la página, usted realiza una oferta para comprar el producto y
                    acepta las condiciones de venta y nuestros términos y condiciones. Todos los pedidos están sujetos a
                    la aceptación por nuestra parte y nos reservamos el derecho a rechazar cualquier pedido realizado
                    por usted. Le proporcionaremos una confirmación escrita de su pedido a la dirección de correo
                    electrónico que usted indique al realizar el pedido, pero dicha confirmación no constituirá nuestra
                    aceptación de ese pedido. Indicaremos nuestra aceptación de su oferta cuando hayamos recibido el
                    pago completo por su parte y le enviemos un correo electrónico de confirmación, momento en el cual
                    se establecerá un contrato. Una vez que el pago total se haya recibido, empezaremos a procesar su
                    pedido y crear su cuento personalizado. Una vez que hayamos empezado a hacer su libro, su pedido no
                    podrá ser cancelado. Se requiere el pago total del libro antes de su fabricación y envío. En caso de
                    que no podamos cumplir con un pedido tras aceptar el pago, podemos devolverle su dinero y cancelar
                    el contrato.
                    <br />
                    <br />

                    Podemos revisar, suspender o modificar los productos o servicios en cualquier momento sin previo
                    aviso, del mismo modo que los productos pueden no estar disponibles sin previo aviso. No nos hacemos
                    responsables si cualquier producto o servicio no está disponible.
                    <br />
                    <br />

                    Usted se compromete a que todos los datos que usted nos proporciona a través de la página con el
                    propósito de la compra de productos son correctos, que su tarjeta de crédito o débito, o cualquier
                    forma dinero electrónico que se utiliza es de su propiedad y que hay suficientes fondos o
                    facilidades de crédito para cubrir el coste de los productos. Si el pago no se recibe en su
                    totalidad, no tendremos obligación de ningún tipo de entregar los productos.
                </p>
                <br />
                <br />
                <h3>Precios y pagos</h3>
                <p>El pago de todos los productos se realiza a través de un proveedor externo de servicios de pago.
                    Usted deberá indicar sus datos de pago a dicho proveedor y es posible que también deba aceptar los
                    términos y condiciones adicionales en relación con el uso de ese servicio. No podemos aceptar, y por
                    la presente excluye a la mayor medida permitida por la ley aplicable, cualquier responsabilidad que
                    surja de o en conexión con su uso de dicho – externo - proveedor de pago.
                    <br />
                    <br />

                    Se puede cambiar el precio de cualquier producto antes de que Usted realice el pedido.
                    <br />
                    <br />

                    A pesar de nuestros esfuerzos, algunos de los productos que figuran en la página pueden mostrar un
                    precio incorrecto, o dicho precio puede incrementarse entre el pedido y nuestra aceptación de su
                    pedido. Habitualmente verificamos los precios como parte de nuestros procesos, de modo que, cuando
                    el precio correcto de un producto sea menor que el precio establecido, realizaremos el cargo por el
                    importe más bajo. En caso de que el precio correcto de un producto sea mayor que el precio que
                    aparece en la página, contactaremos con usted para obtener instrucciones o rechazaremos su pedido y
                    le notificaremos de tal rechazo, para que a continuación, pueda volver a pedir al precio correcto si
                    lo desea.
                    <br />
                    <br />

                    Si un error en el precio es obvio e inequívoco y podría haber sido reconocido por usted como tal, no
                    tendremos ninguna obligación de proporcionarle el producto al precio incorrecto (precio más bajo).
                </p>
                <br />
                <br />
                <h3>Aceptación de Entrega</h3>
                <p>Cuando reciba el producto/s deberá inspeccionarlo(s) para detectar cualquier defecto o falta de
                    conformidad antes de firmar y aceptar su buen estado. Si usted firma la aceptación del producto,
                    estará aceptando que éste está en condiciones aceptables. Cualquier paquete no firmado pero aceptado
                    se considerará en buenas condiciones.
                    <br />
                    <br />

                    Si usted observa cualquier daño en el paquete, por favor, indique que está dañado, ya que de otro
                    modo no podremos realizar un reembolso o reemplazar el artículo dañado, más allá de sus derechos
                    legales.
                    <br />
                    <br />

                    Si la entrega es rechazada o devuelta debido a una dirección incorrecta, usted deberá pagar una
                    tarifa de devolución.
                </p>
                </p>
            </div>


        </div>


</section>