<div class="page-heading" >
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title-heading" style="color:white">Contacto</h1>
    </div>
</div>
<section class="section section-home">
    <div class="container">
        <div class="row contact">
            <div class="col-sm-6">
                <h4><span style="color: #333; font-size: 21px;">¿Quieres proponernos algo o tienes alguna duda? </span></h4>
                <p><span style="color: #999999; font-size: 16px;">Escríbenos en el formulario de la derecha o en los siguientes medios y te responderemos lo más rápido posible.</span></p>
                <div style=" font-size: 21px; line-height: 1.83; font-weight: 600; letter-spacing: .05em;">
                    <p><a href="mailto:info@micuentomagico.com"><i class="fa fa-envelope-o"></i> info@micuentomagico.com</a></p>
                    <br />
                </div>
                <br />
                <br />
                <h4><span style="color: #333; font-size: 24px;">¡Compártenos en Redes!</span></h4>
                <div style="height:4px; margin: 25px 0 15px; width:100px; background:orange;"></div>
                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s); js.id = id;
                        js.src = 'https://connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v2.11';
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                <div class="fb-like" data-href="https://www.facebook.com/micuentomagicopersonalizado/" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
            </div>
            <div class="col-sm-6">
                <?php
                if(isset($this->_errors) && sizeof($this->_errors)>0) {
                    echo '<div class="alert alert-danger">';
                    echo 'Han habido errores:<br/><br/>';
                    foreach($this->_errors as $error) echo $error.'<br/>';
                    echo '</div>';
                }
                else if (isset($this->_message)) {
                    echo '<div class="alert alert-success">';
                    echo $this->_message.'<br/>';
                    echo '</div>';
                }
                ?>
                <form action="<?=BASE_URL.$this->_controlador?>/submitForm" method="post" class="ajax-form" novalidate="novalidate">
                    <div class="row mb20">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                            <div class="form-item">
                                <label for="name">Nombre *</label><span class="wpcf7-form-control-wrap your-name"><input type="text" name="first_name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" id="name" aria-required="true" aria-invalid="false"></span>
                            </div>
                        </div>
                        <div class=" col-xs-12 col-sm-6 col-md-6 col-lg-6">
                            <div class="form-item">
                                <label for="email">Email *</label><span class="wpcf7-form-control-wrap your-email"><input type="email" name="email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" id="email" aria-required="true" aria-invalid="false"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row mb20">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                            <div class="form-item">
                                <label for="name">Teléfono </label><span class="wpcf7-form-control-wrap phone"><input type="text" name="phone" value="" size="40" class="wpcf7-form-control wpcf7-text" id="phone" aria-invalid="false"></span>
                            </div>
                        </div>
                        <div class=" col-xs-12 col-sm-6 col-md-6 col-lg-6">
                            <div class="form-item">
                                <label for="email">Asunto</label><span class="wpcf7-form-control-wrap web"><input type="text" name="subject" value="" size="40" class="wpcf7-form-control wpcf7-text" id="web" aria-invalid="false"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row mb20">
                        <div class=" col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="form-item">
                                <label for="message">Mensaje*</label><span class="wpcf7-form-control-wrap your-message"><textarea name="message" cols="20" rows="5" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required" id="message" aria-required="true" aria-invalid="false"></textarea></span>
                            </div>
                        </div>
                    </div>
					<div class="row mb20">
					<div class=" col-xs-12">
						<label>
							<input type="checkbox" name="acceptance-279" value="1" style="width:auto !Important; display:inline-block;" aria-invalid="false" required> He leído y acepto los <a target="_blank" rel="nofollow noopener noreferrer" href="/es/terminos-y-condiciones">Términos y condiciones</a> y la <a target="_blank" rel="nofollow noopener noreferrer" href="/es/politica-de-privacidad">Política de Privacidad</a>.</label>
					</div>
					</div>
					
					
                    <div class="row mb20">
                        <div class=" col-xs-12 text-right">
                            <div class="form-submit" "><input type="submit" value="Contactar" style="padding-top:14px; font-size:19px; background:orange; border-radius:15px; color:white; font-family: 'Gloria Hallelujah'; border:0px; " class="wpcf7-form-control wpcf7-submit"></div>
                    </div>
            </div>
            </form>

        </div>
    </div>
    </div>
</section>