<div class="page-heading text-center">
    <h1>Ooops!</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <p class="text-center">
                Vaya! Parece que faltan datos o artículos en tu carrito.
                <br />
                ¡prueba a añadirlos de nuevo!
                <br />
                <br />
                ¡Gracias!
            </p>
            <br />




        </div>
    </div>
</div>
