<div class="page-heading text-center">
    <h1>Pedido Pagado</h1>
</div>


<div class="container">
     <div class="row">
         <div class="col-sm-10 col-sm-offset-1 text-center" >
            <p style="padding:90px 0 180px; font-size:27px;"> El pedido se ha pagado satisfactoriamente.

                <br />En breve recibirás un correo confirmando tu compra.
                <br />
                <br />
                ¡Gracias por confiar en nosotros!</p>
         </div>
     </div>
</div>