<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Dashboard
            </h3>
        </div>
        <a href="<?= ADMIN_URL.$this->_controlador ?>/add" class=' pull-right btn btn-success'><i class=" fa fa-plus"></i> Crear nueva entrada</a>
    </div>
</div>


<div class="m-content">




<div class="row">
					<div class="col-lg-12">
                        <div class="m-portlet">

                            <div class="m-portlet__head">

                                <div class="m-portlet__head-caption">
                                    <div class="m-portlet__head-title">
                                        <h3 class="m-portlet__head-text">
                                            Datos
                                        </h3>

                                    </div>

                                </div>
                            </div>
                            <div class="m-portlet__body">
								
								
								<?php 
								
								//echo '<pre>';print_r($this);echo '</pre>';
								$programa = $this->_data['post']['data'];
								$langs = $this->_data['langs'];
						
								$errors = @$this->_errors; 
								
								if(sizeof(@$errors)>0) {
									echo '<div class="alert alert-danger"><ul>';
									foreach($errors as $error) {
										echo '<li>'.$error.'</li>';
									}
									echo '</ul></div>';
								}
								
								?>
								
								<p class="alert alert-danger">
									Estas a punto de borrar la siguiente programación <?= $programa['id'] ?>. ¿Estás seguro de borrarla?
								</p>
								
								<?php foreach($langs as $k => $v) { ?>
										<div class="box box-color box-bordered lightgrey">
										<div class="box-title">
											<h3>
												<i class="fa fa-bars"></i>
												Datos <?php echo $v['name'].' - '.$v['tagname']; ?>
											</h3>
										</div>
									
										<div class="box-content">
										
											<?php 	
											$errors = @$this->_errors; 
											
											if(sizeof(@$errors)>0) {
												echo '<div class="alert alert-danger"><ul>';
												foreach($errors as $error) {
													echo '<li>'.$error.'</li>';
												}
												echo '</ul></div>';
											}											?>
											<div class="tab-content">
												<?php	
													$langid =  strtoupper($v['tagname']);
													$langidl =  strtolower($v['tagname']);
													echo '<div class="control-group mt10">
															<label for="title" class="control-label">Título</label>
															<div class="controls">
																<span>'.@$programa['langs'][$langidl]['titulo'].'</span>
															</div>
														</div>
														<div class="control-group mt10">
															<label for="shortdesc" class="control-label">Descripción corta</label>
															<div class="controls">
																<div>'.html_entity_decode(@$programa['langs'][$langidl]['descripcion']).'</div>
															</div>
														</div>';
													?>
				
												</div>		
											</div>		
										</div>		
								<?php } ?>
								
	
								<div class="box box-color box-bordered lightgrey">
									<div class="box-title">
										<h3>Comunes</h3>
									
									</div>
									<div class="box-content">
									
										<div class="row">
											<div class="col-lg-6">
												<div class="control-group">
													<label for="file" class="control-label">Imagen Grande</label>
													<div class="controls">
														<img src="<?= $_layoutParams['public_img']  ?>blog/<?= $programa['img_full'] ?>" style="height:300px" />
													</div>
												</div>		
											</div>		
											<div class="col-lg-6">
											
												<div class="control-group">
													<label for="file" class="control-label">Miniatura</label>
													<div class="controls">
														<img src="<?= $_layoutParams['public_img']  ?>blog/thumbs/<?= $programa['img_thumb'] ?>" style="height:300px"  />
														
													</div>
												</div>	
											</div>	
										</div>	
									</div>
								</div>


                                <form id="frmDeleteProduction" class="form-horizontal" action="<?= ADMIN_URL.$this->_controlador ?>/deleteNoticia" method="POST" enctype="multipart/form-data">
									<input type="hidden" name="id" value="<?= $programa['id'] ?>"/>
								
									<div class="form-actions">
										<button type="submit" class="btn btn-primary">Borrar</button>
										<a href="<?= ADMIN_URL.$this->_controlador ?>" class="btn btn-danger">Cancelar</a>
									</div>
								</form>
								
							</div>
						</div>
						
					</div>
				</div>
			</div>


