<?php
$news = $this->_data['posts'];
//echo '<pre>'; print_r($news); echo '</pre>';
?>

<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Dashboard
            </h3>
        </div>
        <a href="<?= ADMIN_URL.$this->_controlador ?>/add" class=' pull-right btn btn-success'><i class=" fa fa-plus"></i> Crear nueva entrada</a>
    </div>
</div>


<?php
if($news['error']>0) {
    echo ' <div class="row-fluid">
							<div class="col-lg-12">
								<div class="box box-color alert alert-danger">
									<h3>Error!</h3>';
    echo (isset($news['msg']) && $news['msg']=!'') ? 'Error: '.$news['msg'] : 'Unknown error.';
    echo '	</div>
							</div>
						</div>';

}
if(!isset($news['data']) || sizeof($news['data'])==0) {
    echo ' <div class="row-fluid">
							<div class="col-lg-12">
								<div class="box box-color alert alert-warning">
									<h3>No hay noticias.</h3>';
    echo '	</div>
							</div>
						</div>';

}
?>


<div class="m-content">

    <!-- END: Subheader -->

    <div class="m-portlet">

        <div class="m-portlet__head">

            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Posts List
                    </h3>

                </div>

            </div>
        </div>
        <div class="m-portlet__body">
            <!--begin::Section-->
            <div class="m-section m-section--last">
                <div class="m-section__content">

                    <table class="table table-hover table-nomargin dataTable table-bordered">
                        <thead>
                        <tr>
                            <th width="50">ID</th>

                            <th width="70">Fecha</th>
                            <th  width="170">Nombre</th>

                            <th width="70">Visible</th>

                            <th width="70">Destacada</th>

                            <th width="60">Miniatura</th>

                            <th width="60">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        //echo '<pre>';print_r($news['data']);echo '</pre>';
                        if(isset($news['data']) &&  sizeof($news['data'])>0)
                            foreach($news['data'] as $k => $row) {?>
                                <tr>
                                    <td><?= $row['id'] ?></td>
                                    <td><?= date('d/m/Y H:i:s', (!empty($row['fecha'])) ? $row['fecha'] : time());?></td>

                                    <td><?= $row['titulo'] ?></td>

                                    <td class="text-center"><?= (($row['publicar']==1) ? '<i class="fa fa-eye" style="font-size:15px; background:#60d02a; padding: 10px;  color:#fff;"></i>':'<i style="font-size:15px; color:#fff; padding: 10px; background: #ff0000; " class="fa fa-eye-slash"></i>') ?></td>
                                    <td class="text-center"><?= (($row['destacada']==1) ? '<i class="fa fa-check" style="font-size:15px; background:#60d02a; padding: 10px;  color:#fff;"></i>':'<i style="font-size:15px; color:#fff; padding: 10px; background: #ff0000; " class="fa fa-times"></i>') ?></td>


                                    <td style="text-align:center"><img style="display: block; height: 70px;" src="<?= $_layoutParams['public_img'] .$this->_controlador ?>/thumbs/<?= $row['img_thumb'] ?>" style="height: 40px; width: 150px"/></td>

                                    <td>
                                        <a href="<?= ADMIN_URL.$this->_controlador ?>/edit/<?= $row['id'] ?>" title="Modificar" class="btn btn-xs btn-warning">&nbsp;<i class="icon fa fa-pencil">&nbsp;</i></a>
                                        <a href="<?= ADMIN_URL.$this->_controlador ?>/delete/<?= $row['id'] ?>" title="Borrar" class="btn btn-xs btn-danger">&nbsp;<i class="icon fa fa-trash-o">&nbsp;</i></a>
                                    </td>
                                </tr>
                                <?php
                            }
                        ?>


                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>





