<?php
$noticia = @$this->_data['news']['data'];

$lastNew = $this->_data['lastNew']['data'];
$categorias = $this->_data['categoriasBlog']['data'];

if (!$noticia) {
    echo '<h1>No existe</h1>';
} else {
    ?>

    <div class="page-heading">
        <div class="overlay"></div>
        <div class=" text-center">
             <h1><?php echo($noticia['titulo']) ?></h1>
			 <div class="post_date" style="color:white"><span class="day"><?= date('d', $noticia['fecha']) ?> / <?= date('m', $noticia['fecha']) ?> / <?= date('Y', $noticia['fecha']) ?></span></div>
        </div>
    </div>

<style>
    .desciprcion-larga {margin-top: 20px; font-family:roboto; line-height:1.8em; color:#888;}
	
	.rrssb-buttons.large-format li a, .rrssb-buttons.large-format li a .text {
  -webkit-backface-visibility: hidden;
  -moz-backface-visibility: hidden;
  -ms-backface-visibility: hidden;
}

.rrssb-buttons, .rrssb-buttons li, .rrssb-buttons li a {
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

.clearfix {
  *zoom: 1;
}
.clearfix:after {
  clear: both;
}
.clearfix:before, .clearfix:after {
  content: " ";
  display: table;
}

.rrssb-buttons {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  height: 36px;
  margin: 0;
  padding: 0;
  width: 100%;
}
.rrssb-buttons li {
  float: left;
  height: 100%;
  list-style: none;
  margin: 0;
  padding: 0 2.5px;
  line-height: 13px;
}
.rrssb-buttons li.email a {
  background-color: #0a88ff;
}
.rrssb-buttons li.email a:hover {
  background-color: #006ed6;
}
.rrssb-buttons li.facebook a {
  background-color: #306199;
}
.rrssb-buttons li.facebook a:hover {
  background-color: #244872;
}
.rrssb-buttons li.tumblr a {
  background-color: #32506d;
}
.rrssb-buttons li.tumblr a:hover {
  background-color: #22364a;
}
.rrssb-buttons li.linkedin a {
  background-color: #007bb6;
}
.rrssb-buttons li.linkedin a:hover {
  background-color: #005983;
}
.rrssb-buttons li.twitter a {
  background-color: #26c4f1;
}
.rrssb-buttons li.twitter a:hover {
  background-color: #0eaad6;
}
.rrssb-buttons li.googleplus a {
  background-color: #e93f2e;
}
.rrssb-buttons li.googleplus a:hover {
  background-color: #ce2616;
}
.rrssb-buttons li.youtube a {
  background-color: #df1c31;
}
.rrssb-buttons li.youtube a:hover {
  background-color: #b21627;
}
.rrssb-buttons li.reddit a {
  background-color: #8bbbe3;
}
.rrssb-buttons li.reddit a:hover {
  background-color: #62a3d9;
}
.rrssb-buttons li.pinterest a {
  background-color: #b81621;
}
.rrssb-buttons li.pinterest a:hover {
  background-color: #8a1119;
}
.rrssb-buttons li.pocket a {
  background-color: #ED4054;
}
.rrssb-buttons li.pocket a:hover {
  background-color: #e4162d;
}
.rrssb-buttons li.github a {
  background-color: #444;
}
.rrssb-buttons li.github a:hover {
  background-color: #2b2b2b;
}
.rrssb-buttons li a {
  background-color: #ccc;
  border-radius: 0;
  display: block;
  font-size: 11px;
  font-weight: bold;
  height: 100%;
  padding: 11px 7px 12px 27px;
  position: relative;
  text-align: center;
  text-decoration: none;
  text-transform: uppercase;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  width: 100%;
  -webkit-transition: background-color 0.2s ease-in-out;
  -moz-transition: background-color 0.2s ease-in-out;
  -o-transition: background-color 0.2s ease-in-out;
  transition: background-color 0.2s ease-in-out;
}
.rrssb-buttons li a .icon {
  display: block;
  height: 100%;
  left: 10px;
  padding-top: 9px;
  position: absolute;
  top: 0;
  width: 10%;
}
.rrssb-buttons li a .icon svg {
  height: 17px;
  width: 17px;
}
.rrssb-buttons li a .icon svg path, .rrssb-buttons li a .icon svg polygon {
  fill: #fff;
}
.rrssb-buttons li a .text {
  color: #fff;
}
.rrssb-buttons li a:active {
  box-shadow: inset 1px 3px 15px 0 rgba(22, 0, 0, 0.25);
}
.rrssb-buttons li.small a {
  padding: 0;
}
.rrssb-buttons li.small a .icon {
  height: 100%;
  left: auto;
  margin: 0 auto;
  overflow: hidden;
  position: relative;
  top: auto;
  width: 100%;
}
.rrssb-buttons li.small a .text {
  visibility: hidden;
  margin-left:10px;
}
.rrssb-buttons.large-format {
  height: auto;
}
.rrssb-buttons.large-format li {
  height: auto;
}
.rrssb-buttons.large-format li a {
  font-size: 15px;
  font-size: 1vw;
  padding: 7% 0% 7% 12%;
  border-radius: 0.2em;
  line-height: 1vw;
}
.rrssb-buttons.large-format li a .icon {
  left: 7%;
  padding-top: 0;
  width: 12%;
  margin-right:10px;
}
.rrssb-buttons.large-format li a .icon svg {
  height: 100%;
  width: 100%;
}
.rrssb-buttons.large-format li a .text {
  font-size: 15px;
  font-size: 1vw;
}
.rrssb-buttons.large-format li a:hover {
  font-size: 15px;
  font-size: 1vw;
  padding: 7% 0% 7% 12%;
  border-radius: 0.2em;
}
.rrssb-buttons.small-format {
  padding-top: 5px;
}
.rrssb-buttons.small-format li {
  height: 80%;
  padding: 0 1.5px;
}
.rrssb-buttons.small-format li a .icon {
  height: 100%;
  padding-top: 0;
}
.rrssb-buttons.small-format li a .icon svg {
  height: 48%;
  position: relative;
  top: 6px;
  width: 80%;
}
.rrssb-buttons.tiny-format {
  height: 22px;
  position: relative;
}
.rrssb-buttons.tiny-format li {
  padding-right: 7px;
}
.rrssb-buttons.tiny-format li a {
  background-color: transparent;
  padding: 0;
}
.rrssb-buttons.tiny-format li a .icon svg {
  height: 70%;
  width: 100%;
}
.rrssb-buttons.tiny-format li a:hover, .rrssb-buttons.tiny-format li a:active {
  background-color: transparent;
}
.rrssb-buttons.tiny-format li.email a .icon svg path, .rrssb-buttons.tiny-format li.email a .icon svg polygon {
  fill: #0a88ff;
}
.rrssb-buttons.tiny-format li.email a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.email a .icon:hover .icon svg polygon {
  fill: #0054a3;
}
.rrssb-buttons.tiny-format li.facebook a .icon svg path, .rrssb-buttons.tiny-format li.facebook a .icon svg polygon {
  fill: #306199;
}
.rrssb-buttons.tiny-format li.facebook a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.facebook a .icon:hover .icon svg polygon {
  fill: #18304b;
}
.rrssb-buttons.tiny-format li.tumblr a .icon svg path, .rrssb-buttons.tiny-format li.tumblr a .icon svg polygon {
  fill: #32506d;
}
.rrssb-buttons.tiny-format li.tumblr a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.tumblr a .icon:hover .icon svg polygon {
  fill: #121d27;
}
.rrssb-buttons.tiny-format li.linkedin a .icon svg path, .rrssb-buttons.tiny-format li.linkedin a .icon svg polygon {
  fill: #007bb6;
}
.rrssb-buttons.tiny-format li.linkedin a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.linkedin a .icon:hover .icon svg polygon {
  fill: #003650;
}
.rrssb-buttons.tiny-format li.twitter a .icon svg path, .rrssb-buttons.tiny-format li.twitter a .icon svg polygon {
  fill: #26c4f1;
}
.rrssb-buttons.tiny-format li.twitter a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.twitter a .icon:hover .icon svg polygon {
  fill: #0b84a6;
}
.rrssb-buttons.tiny-format li.googleplus a .icon svg path, .rrssb-buttons.tiny-format li.googleplus a .icon svg polygon {
  fill: #e93f2e;
}
.rrssb-buttons.tiny-format li.googleplus a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.googleplus a .icon:hover .icon svg polygon {
  fill: #a01e11;
}
.rrssb-buttons.tiny-format li.youtube a .icon svg path, .rrssb-buttons.tiny-format li.youtube a .icon svg polygon {
  fill: #df1c31;
}
.rrssb-buttons.tiny-format li.youtube a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.youtube a .icon:hover .icon svg polygon {
  fill: #84111d;
}
.rrssb-buttons.tiny-format li.reddit a .icon svg path, .rrssb-buttons.tiny-format li.reddit a .icon svg polygon {
  fill: #8bbbe3;
}
.rrssb-buttons.tiny-format li.reddit a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.reddit a .icon:hover .icon svg polygon {
  fill: #398bcf;
}
.rrssb-buttons.tiny-format li.pinterest a .icon svg path, .rrssb-buttons.tiny-format li.pinterest a .icon svg polygon {
  fill: #b81621;
}
.rrssb-buttons.tiny-format li.pinterest a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.pinterest a .icon:hover .icon svg polygon {
  fill: #5d0b11;
}
.rrssb-buttons.tiny-format li.pocket a .icon svg path, .rrssb-buttons.tiny-format li.pocket a .icon svg polygon {
  fill: #ED4054;
}
.rrssb-buttons.tiny-format li.pocket a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.pocket a .icon:hover .icon svg polygon {
  fill: #b61124;
}
.rrssb-buttons.tiny-format li.github a .icon svg path, .rrssb-buttons.tiny-format li.github a .icon svg polygon {
  fill: #444;
}
.rrssb-buttons.tiny-format li.github a .icon:hover .icon svg path, .rrssb-buttons.tiny-format li.github a .icon:hover .icon svg polygon {
  fill: #111111;
}



</style>
    <section  style="" class="" role="main">
        <div id="" class="section container mb30 mt50 ">
            <div class="page-main">
                <div class="">

                    <div class="row">

                        <div class="col-sm-8 col-md-8 col-lg-8">
                            <div class="blog_large">

                                <br/>
                                <?php

                                $categorias_html = '';
                                if (isset($noticia['categoriasBlog'])) {
                                    $categorias_html = '<strong>Categorías: </strong>';
                                    foreach ($noticia['categoriasBlog'] as $categoria) $categorias_html .= '<a class="btag" href="' . BASE_URL . $this->_lang . DS . 'blog' . DS . 'categoria' . DS . $categoria['slug'] . '">' . $categoria['nombre'] . '</a>';
                                }
								
								$url_share = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

                                ?>

                                <!-- Post Static Image Start-->
                                <article class="post noticia_lista" date="<?= $noticia['fecha'] ?>">
                                    <div class="post_content medium">
                                        <figure class="post_img"><img src="<?= $_layoutParams['public_img'] . 'blog' . DS . $noticia['img_full'] ?>" style="margin: 0 auto; display:block; width:100%;;" alt=" "></figure>
										
										<div class="share-links" style="margin-top:20px;">
										<div class="inline-block;" style="color:rgb(42,158,209); margin-bottom:10px; font-size:20px;">Comparte la noticia!</div>
										<ul class="rrssb-buttons clearfix">
											<li class="facebook">
												<!-- Replace with your URL. For best results, make sure you page has the proper FB Open Graph tags in header: 
												https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content/ -->
												<a target="_BLANK" href="https://www.facebook.com/sharer/sharer.php?u=<?=$url_share?>" class="popup">
													<span class="icon">
														<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
															<path d="M27.825,4.783c0-2.427-2.182-4.608-4.608-4.608H4.783c-2.422,0-4.608,2.182-4.608,4.608v18.434
																c0,2.427,2.181,4.608,4.608,4.608H14V17.379h-3.379v-4.608H14v-1.795c0-3.089,2.335-5.885,5.192-5.885h3.718v4.608h-3.726
																c-0.408,0-0.884,0.492-0.884,1.236v1.836h4.609v4.608h-4.609v10.446h4.916c2.422,0,4.608-2.188,4.608-4.608V4.783z"/>
														</svg>
													</span>
													<span class="text">facebook</span>
												</a>
											</li>
											<li class="twitter">
												<!-- Replace href with your Meta and URL information  -->
												<a target="_BLANK" href="https://twitter.com/home?status=<?=$url_share?>" class="popup">
													<span class="icon">
														<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
															 width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
														<path d="M24.253,8.756C24.689,17.08,18.297,24.182,9.97,24.62c-3.122,0.162-6.219-0.646-8.861-2.32
															c2.703,0.179,5.376-0.648,7.508-2.321c-2.072-0.247-3.818-1.661-4.489-3.638c0.801,0.128,1.62,0.076,2.399-0.155
															C4.045,15.72,2.215,13.6,2.115,11.077c0.688,0.275,1.426,0.407,2.168,0.386c-2.135-1.65-2.729-4.621-1.394-6.965
															C5.575,7.816,9.54,9.84,13.803,10.071c-0.842-2.739,0.694-5.64,3.434-6.482c2.018-0.623,4.212,0.044,5.546,1.683
															c1.186-0.213,2.318-0.662,3.329-1.317c-0.385,1.256-1.247,2.312-2.399,2.942c1.048-0.106,2.069-0.394,3.019-0.851
															C26.275,7.229,25.39,8.196,24.253,8.756z"/>
														</svg>
												   </span>
													<span class="text">twitter</span>
												</a>
											</li>
											
											<li class="linkedin">
												<!-- Replace href with your meta and URL information -->
												<a target="_BLANK" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?=$url_share?>" class="popup">
													<span class="icon">
														<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
															<path d="M25.424,15.887v8.447h-4.896v-7.882c0-1.979-0.709-3.331-2.48-3.331c-1.354,0-2.158,0.911-2.514,1.803
																c-0.129,0.315-0.162,0.753-0.162,1.194v8.216h-4.899c0,0,0.066-13.349,0-14.731h4.899v2.088c-0.01,0.016-0.023,0.032-0.033,0.048
																h0.033V11.69c0.65-1.002,1.812-2.435,4.414-2.435C23.008,9.254,25.424,11.361,25.424,15.887z M5.348,2.501
																c-1.676,0-2.772,1.092-2.772,2.539c0,1.421,1.066,2.538,2.717,2.546h0.032c1.709,0,2.771-1.132,2.771-2.546
																C8.054,3.593,7.019,2.501,5.343,2.501H5.348z M2.867,24.334h4.897V9.603H2.867V24.334z"/>
														</svg>
													</span>
													<span class="text">linkedin</span>
												</a>
											</li>
										</ul>
										</div>
										
                                        <div class="post_meta">
                                           
                                            

                                            <div class="metaInfo">
                                                <?= @$categorias_html ?>
                                            </div>
                                            <div class="desciprcion-larga"><?php echo html_entity_decode($noticia['descripcion']) ?></div>
                                        </div>
                                </article>
                                <!-- Post Static Image End-->

                            </div>

                        </div>

                        <!--Sidebar Widget-->
                        <div class="col-sm-4 col-md-4 col-lg-4 ">
                            <div class="sidebar_widget">


                                <?php include('parts/sidebar/buscar.phtml'); ?>

                                <br />
                                <br />

                                <?php include('parts/categorias_lista.phtml'); ?>

                                <br />
                                <br />
                                <?php include('parts/sidebar/recent_posts.phtml'); ?>



                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                </div>
                <span class="offset-40 md-offset-15"></span>
                <span class="offset-40 md-offset-15"></span>

            </div>
        </div>
    </section>

<?php } ?>