<div class="book-heading" style="padding:3vw 0; background-image: url(http://cuentos.dev/public/img/bookbg.jpg);background-position: center;
    background-size: 100%;
    background-repeat: no-repeat;">
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title" style="color:white">Preguntas Frecuentes</h1>
    </div>
</div>
<style>
    .mb20 {
        margin-bottom: 20px;
    }

    .overlay {
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
        background: rgba(0, 0, 0, .3);
    }

    .contact ul li a {
        padding: 10px;
        display: block;
        color: #29abe2;
    }

    .social-contact {
        list-style: none
    }

    .social-contact li {
        border-bottom: 0px !important;
        list-style: none;
        display: inline-block;
        margin: 2px 5px;
    }

    .social-contact li a {
        text-decoration: none !important;
        border: 1px dashed #29abe2;
        height: 40px;
        width: 40px;
        text-align: center;
        line-height: 1.3em;
        color: #29abe2;
        font-size: 16px;
        border-radius: 100%;
    }

    .social-contact li a:hover {
        color: #333;
    } .team-member {font-family: 'Gloria Hallelujah'; color:#29abe2; text-align:center; font-size:43Px;}
    .nombre {font-family: 'Gloria Hallelujah'; color:#29abe2; text-align:center; font-size:43Px;}

    .puesto {

        font-family:"Gloria Hallelujah"; font-size:20px; color:#333;}
    .descripcion {margin-top: 20px;}

</style>
<section class="section section-home">
    <div class="container">
        <link href="https://fonts.googleapis.com/css?family=Stalemate" rel="stylesheet">

        <div class="row contact">
            <div class="col-sm-12">
                <p><strong>&iquest;Para qui&eacute;n es?</strong></p>
                <p>El cuento es para ni&ntilde;os de entre 0 y 9 a&ntilde;os.</p>
                <p>&nbsp;</p>
                <p><strong>¿Cómo es?</strong></p>
                <p>
                    El cuento en formato físico mide 21x21 cm, una medida ergonómica y cómoda para los peques. Son 42 páginas con 20 ilustraciones a doble cara impresas a todo color en papel estucado mate de 170 gramos y cubiertas de 350 gramos en papel estucado brillo.
                   <br />
                    También tienes la opción de formato digital para leer en e-books, tablets, etc
                </p>
                <p>&nbsp;</p>
                <p><strong>&iquest;Cu&aacute;nto cuesta?</strong></p>
                <p>El cuento dispone de diferentes tarifas:</p>
                <ul>
                    <li> - E-Book 6.95€</li>
                    <li> - Libro Tapa Blanda: 22.95€</li>
                    <li> - Pack Libro + E-Book 27.95€</li>
                </ul>
                <p>&nbsp;</p>
                <p><strong>¿Cuánto cuesta el envío?</strong></p>
                <p>El envío es gratis. Enviamos a España peninsular y Baleares.</p>
                <p>&nbsp;</p>
                <p><strong>&iquest;Cu&aacute;nto tarda?</strong></p>
                <p>Todos los libros son personalizados y se imprimen exclusivamente para ti. El plazo aproximado de entrega es de 7 a 10 d&iacute;as.</p>
                <p>&nbsp;</p>
                <p><strong>&iquest;C&oacute;mo puedo pagar?</strong></p>
                <p>Aceptamos pagos con tarjeta de d&eacute;bito o cr&eacute;dito, Paypal y transferencia bancaria.</p>
                <p>&nbsp;</p>
                <p><strong>&iquest;Acept&aacute;is pagos contra-reembolso?</strong></p>
                <p>Nuestros cuentos son personalizados y se fabrican exclusivamente para cada cliente por lo que no podemos aceptar pagos contrareembolso para evitar problemas de devoluciones.</p>
                <p>&nbsp;</p>
                <p><strong>&iquest;C&oacute;mo puedo aplicar un cup&oacute;n de descuento?</strong></p>
                <p>Cuando hayas a&ntilde;adido tu cuento al carrito, encontrar&aacute;s un cuadro de texto en el que podr&aacute;s introducir tu c&oacute;digo.</p>
                <p>&nbsp;</p>
                <p><strong>Acabo de recibir mi pedido y tiene un defecto, &iquest;qu&eacute; puedo hacer?</strong></p>
                <p>Tienes que avisarnos lo antes posible indicando tu n&uacute;mero de pedido a trav&eacute;s de nuestro formulario de contacto o correo electr&oacute;nico.</p>
                <p>&nbsp;</p>
                <p><strong>&iquest;Se incluye la factura en el paquete?</strong></p>
                <p>No se incluye la factura, pero si necesitas factura, podr&aacute;s solicitarla y te la enviamos por correo electr&oacute;nico</p>
                <p>&nbsp;</p>
                <p><strong>&iquest;Se puede personalizar totalmente un cuento?</strong></p>
                <p>Si tienes la idea de hacer un pedido de cierto n&uacute;mero de ejemplares, escribiendo t&uacute; la historia, se valorar&iacute;a y se te pasar&iacute;a un presupuesto. Si lo que quieres es un cuento totalmente personalizado, tanto historia como dibujos, contamos con varios ilustradores que se pueden adecuar al estilo de dibujo que buscas y te pasar&iacute;amos presupuesto.</p>
                <p>&nbsp;</p>
                <p>&nbsp;</p>


            </div>


        </div>




</section>