<?php
//THE PRODUCT


$product = $this->_data['users']['data'][0];



$errors = @$this->_errors;

if(sizeof(@$errors)>0) {
    echo '<div class="alert alert-danger"><ul>';
    foreach($errors as $error) {
        echo '<li>'.$error.'</li>';
    }
    echo '</ul></div>';
}

if(@$this->_updated>0) {
    echo '<div class="alert alert-success"><p>Se ha actualizado exitosamente.</p></div>';
}
else if (@$this->_updated==-1) {
    echo '<div class="alert alert-warning"><p>No se ha podido actualizar.</p></div>';
}
?>



    <?php
    /*
    echo '<pre>';
    print_r( $this->_data);
    echo '</pre>';
    */
    /*
    echo '<pre>';
        print_r($filters);
    echo '</pre>';
    */

    /*
    echo "<xmp>";
        print_r(get_defined_vars());
    echo "</xmp>";
    */



    ?>

<style>
    .white-box {
        background:white;
        padding:20px;
        margin-bottom:10px;
    }
</style>
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Editar
            </h3>
        </div>
    </div>
</div>

<div class="m-content">

<?php
      //  print_r($product);
        ?>
<form id="frmNewNew" class="form-vertical form-bordered" action="<?= BASE_URL.$this->_controlador ?>/action_edit" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="d[id]" value="<?= $product['id'] ?>" />


        <div class="row">





            <div class="col-lg-9">

                <div class="m-portlet">

                    <div class="m-portlet__head">

                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    Datos de sesión
                                </h3>

                            </div>

                        </div>
                    </div>
                    <div class="m-portlet__body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="control-group">
                                            <label for="username" class="control-label">Nombre de usuario</label>
                                            <div class="controls">
                                                <input type="text" id="username" class="form-control" name="d[username]" value="<?php echo @$product['login']?>" />
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="password" class="control-label">Contraseña</label>
                                            <div class="controls">
                                                <input type="password" id="password" class="form-control" name="d[password]" value="" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="repassword" class="control-label">Repite Contraseña</label>
                                            <div class="controls">
                                                <input type="password" id="repassword" class="form-control" name="d[repassword]" value="" />
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>



                <div class="m-portlet">

                    <div class="m-portlet__head">

                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    Datos del usuario
                                </h3>

                            </div>

                        </div>
                    </div>
                    <div class="m-portlet__body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="username" class="control-label">Nombre</label>
                                            <div class="controls">
                                                <input type="text" id="username" class="form-control" name="d[first_name]" value="<?php echo @$product['first_name']?>" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="username" class="control-label">Apellidos</label>
                                            <div class="controls">
                                                <input type="text" id="username" class="form-control" name="d[last_name]" value="<?php echo @$product['last_name']?>" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="email" class="control-label">E-mail</label>
                                            <div class="controls">
                                                <input type="email" id="email" class="form-control" name="d[email]" value="<?php echo @$product['email']?>" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="phone" class="control-label">Teléfono Fijo</label>
                                            <div class="controls">
                                                <input type="text" id="phone" class="form-control" name="d[phone]" value="<?php echo @$product['phone']?>" />
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="mobile" class="control-label">Teléfono Móvil</label>
                                            <div class="controls">
                                                <input type="text" id="mobile" class="form-control" name="d[mobile]" value="<?php echo @$product['mobile']?>" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="phone" class="control-label">Sexo</label>
                                            <div class="controls">
                                                <select class="form-control" name="d[gender]">
                                                    <option value="male" <?= (($product['gender']=='male') ? 'selected' : '' )?>>Hombre</option>
                                                    <option value="female" <?= (($product['gender']=='female') ? 'selected' : '' )?>>Mujer</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="address" class="control-label">Dirección</label>
                                            <div class="controls">
                                                <input type="text" id="address" class="form-control" name="d[address]" value="<?php echo @$product['address']?>" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="address_bill" class="control-label">Dirección FACTURACIÓN</label>
                                            <div class="controls">
                                                <input type="text" id="address_bill" class="form-control" name="d[address_bill]" value="<?php echo @$product['address_bill']?>" />
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="control-group">
                                            <label for="address" class="control-label">Idioma principal</label>
                                            <div class="controls">

                                                <select class="form-control" name="d[user_lang]">
                                                    <?php
                                                        foreach(Languages::getLangsDB() as $lang) echo '<option value="'.$lang['tagname'].'" '.(($product['user_lang']==$lang['tagname']) ? 'selected':'').' >'.$lang['name'].'</option>';
                                                    ?>
                                                </select>

                                            </div>
                                        </div>
                                    </div>

                                </div>



                            </div>
                        </div>



                </div>

                <div class="col-lg-3" id="">
                    <div class="m-portlet">

                        <div class="m-portlet__head">

                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text">
                                        Acciones
                                    </h3>

                                </div>

                            </div>
                        </div>
                        <div class="m-portlet__body">







                            <div class="form-actions">
                                <input type="hidden" name="c[id]" value="<?= $product["id"] ?>" />
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a href="<?= BASE_URL.$this->_controlador ?>/lista" class="btn btn-danger">Cancelar</a>
                            </div>

                        </div>
                    </div>
                    <div class="m-portlet">

                        <div class="m-portlet__head">

                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text">
                                        Estado
                                    </h3>

                                </div>

                            </div>
                        </div>
                        <div class="m-portlet__body">
                            <div class="row">

                                <div class="col-sm-4">
                                    <div class="control-group">
                                        <label for="active" class="control-label">Activo</label>
                                        <div class="controls">
                                            <input type="checkbox" id="active" class="js-switch" data-color="#13dafe" name="d[active]" <?= (($product['active']>0) ? 'checked' : 'nchecked' )?> />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="control-group">
                                        <label for="banned" class="control-label">Banned</label>
                                        <div class="controls">
                                            <input type="checkbox" class="js-switch" data-color="#13dafe" id="banned"  name="d[banned]" <?= (($product['banned']>0) ? 'checked' : 'nchecked' )?> />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="control-group">
                                        <label for="newsletter" class="control-label">Newsletter</label>
                                        <div class="controls">
                                            <input type="checkbox" id="newsletter" class="js-switch" data-color="#13dafe" name="d[newsletter]" <?= (($product['newsletter']>0) ? 'checked' : 'nchecked' )?> />
                                        </div>
                                    </div>
                                </div>
                            </div>



                        </div>
                    </div>




                </div>

            </div>
        </div>
</form>
</div>

