<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Dashboard
            </h3>
        </div>

    </div>
</div>

<div class="m-content">

    <!-- END: Subheader -->

    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Grid Nav
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <!--begin::Section-->
            <div class="m-section m-section--last">
                <div class="m-section__content">
                    <!--begin::Preview-->
                    <div class="m-demo" data-code-preview="true" data-code-html="true" data-code-js="false">
                        <div class="m-demo__preview">
                            <div class="m-nav-grid">
                                <div class="m-nav-grid__row">
                                    <a href="<?=ADMIN_URL?>pedidos" class="m-nav-grid__item">
                                        <i class="m-nav-grid__icon flaticon-coins"></i>
                                        <span class="m-nav-grid__text">
                                            Ver Pedidos
                                        </span>
                                    </a>
                                    <a href="<?=ADMIN_URL?>blog" class="m-nav-grid__item">
                                        <i class="m-nav-grid__icon flaticon-file"></i>
                                        <span class="m-nav-grid__text">
                                            Crear Post
                                        </span>
                                    </a>

                                     <a href="<?=ADMIN_URL?>cupones" class="m-nav-grid__item">
                                        <i class="m-nav-grid__icon flaticon-clipboard"></i>
                                        <span class="m-nav-grid__text">
                                            Crear Cupón
                                        </span>
                                    </a>


                                </div>

                            </div>
                        </div>
                    </div>
                    <!--end::Preview-->

                </div>
            </div>
            <!--end::Section-->
        </div>
    </div>
    <!--end::Portlet-->

</div>