<div class="sw_archives">
    <div class="sw_title">
        <h4>ENTRADAS RECIENTES</h4>
        <div class="brb"></div>
    </div>
    <ul class="archives_list">
        <?php
        foreach ($lastNew as $new) {
            echo '<li><a href="' . BASE_URL . $this->_lang . DS . 'blog' . DS . 'ver' . DS . $new['slug'] . '">' . $new['titulo'] . '</a></li>';
        }
        ?>
    </ul>
</div>

<style>


    .archives_list li  {margin-bottom: 5px;  }
    .archives_list li a {transition:all .3s ease-in-out; display:block; padding:5px 25px; border:1px solid #29abe2; border-radius:15px;  }
    .archives_list li a:hover {background: #29abe2; color:white;  }


</style>