<?php
    $menu = array(
            'pedidos'=>array(
                'name'=>'Pedidos',
                'url'=>ADMIN_URL.'pedidos',
                'items'=>array(
                    'ver_todos'=>array(
                        'name'=>'Lista Pedidos',
                        'url'=>ADMIN_URL.'pedidos',
                    ),
                    'pendientes_pago_transfer'=>array(
                        'name'=>'Pendientes Transfer',
                        'url'=>ADMIN_URL.'pedidos/index/pendientes-transfer',
                    ),
                    'no-pagados'=>array(
                        'name'=>'No pagados',
                        'url'=>ADMIN_URL.'pedidos/index/no-pagados',
                    ),
                    'no_enviados_imprenta'=>array(
                        'name'=>'Pagados y NO IMPRESOS',
                        'url'=>ADMIN_URL.'pedidos/index/pagados-y-no-enviados-imprenta',
                    ),
                    'pagados'=>array(
                        'name'=>'Pagados y IMPRESOS',
                        'url'=>ADMIN_URL.'pedidos/index/pagados-y-en-impresion',
                    ),
                    'completados'=>array(
                        'name'=>'Completados',
                        'url'=>ADMIN_URL.'pedidos/index/completados',
                    ),
                    'cancelados'=>array(
                        'name'=>'Cancelados',
                        'url'=>ADMIN_URL.'pedidos/index/cancelados',
                    ),


                )
            ),
            'blog'=>array(
                'name'=>'Blog',
                'url'=>ADMIN_URL.'blog',
                'items'=>array(
                    'ver_todos'=>array(
                        'name'=>'Ver Artículos',
                        'url'=>ADMIN_URL.'blog',
                    ),
                    'anadir'=>array(
                        'name'=>'Añadir Post',
                        'url'=>ADMIN_URL.'blog/add',
                    ),


                )
            ),
            'pedidos_impresion'=>array(
                'name'=>'Impresion Pedidos',
                'url'=>ADMIN_URL.'pedidos/detalles_impresion',
                'items'=>array(
                )
            ),
            'categorias_blog'=>array(
                'name'=>'Categorias Blog',
                'url'=>ADMIN_URL.'categorias_blog',
                'items'=>array()
            ),
            'cupones'=>array(
                'name'=>'Cupones',
                'url'=>ADMIN_URL.'cupones',
                'items'=>array(
                    'ver_todos'=>array(
                        'name'=>'Ver Cupones',
                        'url'=>ADMIN_URL.'cupones',
                    ),
                    'anadir'=>array(
                        'name'=>'Crear Nuevo',
                        'url'=>ADMIN_URL.'cupones/add',
                    ),


                )
            )
    );


?>


<!-- BEGIN: Left Aside -->
<button class="m-aside-left-close  m-aside-left-close--skin-dark " id="m_aside_left_close_btn">
    <i class="la la-close"></i>
</button>
<div id="m_aside_left" class="m-grid__item    m-aside-left  m-aside-left--skin-dark ">
    <!-- BEGIN: Aside Menu -->
    <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark " data-menu-vertical="true" data-menu-scrollable="false" data-menu-dropdown-timeout="500">
        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
            <li class="m-menu__section">
                <hr />
            </li>


            <li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
                <a href="<?=ADMIN_URL?>" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title"> <span class="m-menu__link-wrap"> <span class="m-menu__link-text"> Dashboard</span></span>
                </a>
            </li>
            <li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
                <a href="<?=MENU_URL?>" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-browser"></i>
                    <span class="m-menu__link-title"> <span class="m-menu__link-wrap"> <span class="m-menu__link-text"> Web</span></span>
                </a>
            </li>
            <li class="m-menu__section">
                <h4 class="m-menu__section-text">
                    Administración
                </h4>
                <i class="m-menu__section-icon flaticon-more-v3"></i>
            </li>



            <?php
                foreach($menu as $menu_item) {
                     ?>
                    <li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" data-menu-submenu-toggle="hover">
                        <a href="<?=$menu_item['url']?>" class="m-menu__link m-menu__toggle">
                            <i class="m-menu__link-icon flaticon-layers"></i>
                            <span class="m-menu__link-text"><?=$menu_item['name']?> </span>
                            <i class="m-menu__ver-arrow la la-angle-right"></i>
                        </a>
                        <?php
                        if($menu_item['items']) {
                            foreach($menu_item['items'] as $menu_subitem) {
                                ?>
                                <div class="m-menu__submenu">
                                    <span class="m-menu__arrow"></span>
                                    <ul class="m-menu__subnav">
                                        <li class="m-menu__item " aria-haspopup="true">
                                            <a href="<?=$menu_subitem['url']?>" class="m-menu__link ">
                                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"> <span></span></i>
                                                <span class="m-menu__link-text"><?=$menu_subitem['name']?></span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            <?php
                            }
                        }

                        ?>

                    </li>
                    <?php
                }
            ?>


        </ul>
    </div>
    <!-- END: Aside Menu -->
</div>
<!-- END: Left Aside -->