<div class="slider-container "  >
    <div id="rev_slider_40_1_wrapper" class="hidden-xs slider rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto; padding:0px;margin-top:0px;margin-bottom:0px;">
    <!-- START REVOLUTION SLIDER 5.0 auto mode -->
    <div id="rev_slider_40_1" class="rev_slider " style="overflow:hidden;  height: 510px; background:lightyellow " data-version="5.0">
        <ul>	<!-- SLIDE  -->


            <li data-index="rs-104" data-transition="zoomout" data-slotamount="default" data-masterspeed="3000"   data-rotate="0"  data-saveperformance="off"  data-title="Intro" data-description="">
                <!-- MAIN IMAGE -->
                <img src="<?=$_layoutParams['public_img']?>slider/slider-1/background.jpg"  alt=""  width="1920" height="1080" data-bgposition="bottom center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->


                <!-- RAMAS-LEFT -->
                <div class=" tp-caption   tp-resizeme "
                     data-x="['right','right','right','right']" data-hoffset="['560','560','560','0']"
                     data-y="['bottom','bottom','bottom','bottom']" data-voffset="['5','0','0','0']"
                     data-transform_idle="o:1;"
                     data-transform_in="y:40;opacity:0;s:1200;e:Power2.easeInOut;"
                     data-transform_out="opacity:0;s:1200;s:1200;"
                     data-start="1900"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                    >
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/chico.png"  data-ww="352px" data-hh="252px" />
                </div>

                <!-- RAMAS-LEFT -->
                <div class=" tp-caption   tp-resizeme"
                     data-x="['right','right','right','right']" data-hoffset="['300','300','300','0']"
                     data-y="['bottom','center','center','center']" data-voffset="['0','0','0','0']"
                     data-transform_idle="o:1;"
                     data-transform_in="y:40;opacity:0;s:1200;e:Power2.easeInOut;"
                     data-transform_out="opacity:0;s:300;s:1200;"
                     data-start="1600"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/chica.png"  data-ww="232px" data-hh="242px" />
                </div>

                <!-- VERDE-BOTTOM -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']"
                     data-y="['center','center','center','center']" data-voffset="['-5','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="x:-50px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="950"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/PERRO.png"  data-ww="800px" data-hh="450px"  />
                </div>
                <!-- VERDE-BOTTOM -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"
                     data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:50px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="0"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/BOTTOM.png"  style="z-index: 5;" data-ww="2248px" />
                </div>


                <!-- TOP LEFT GRASS -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']"
                     data-y="['top','top','top','top']" data-voffset="['0','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:-50px;x:-40px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="0"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/IZQUIERDA.png"  data-ww="338px"  data-hh="539px" />
                </div>

                <!-- TOP LEFT GRASS -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']"
                     data-y="['center','center','center','center']" data-voffset="['0','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:50px;x:-40px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="850"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/DIBUJOS_20LEFT.png"  data-ww="138px"  data-hh="539px" />
                </div>

                <!-- VERDE_TOP -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"
                     data-y="['top','top','top','top']" data-voffset="['0','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:-50px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="0"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/TOP.png"/>
                </div>



                <!-- VERDE-BOTTOM -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['right','right','right','right']" data-hoffset="['0','0','0','0']"
                     data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:50px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="0"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/RIGHT.png"  style="z-index: 5;" />
                </div>



                <!-- VERDE-BOTTOM -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['right','right','right','right']" data-hoffset="['0','0','0','0']"
                     data-y="['top','top','top','top']" data-voffset="['0','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:50px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="0"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/DERECHA.png"  data-ww="400px" data-hh="800px"/>
                </div>







                <!-- VERDE-BOTTOM -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['right','right','right','right']" data-hoffset="['270','0','0','0']"
                     data-y="['center','center','center','center']" data-voffset="['-100','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:50px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="2250"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/LIBRO.png"  style="z-index: 5;" data-ww="350px" data-hh="350px"  />
                </div>


                <!-- VERDE-BOTTOM -->
                <div class="tp-caption maincaption   tp-resizeme rs-parallaxlevel-0"
                     id="slide-143-layer-1"
                     data-x="['left','left','left','left']" data-hoffset="['-60','-60','-60','-+0']"
                     data-y="['bottom','bottom','bottom','bottom']" data-voffset="['-5','0','0','0']"
                     data-width="none"  data-height="none"   data-whitespace="nowrap"  data-transform_idle="o:1;"
                     data-transform_in="y:50px;opacity:0;s:2000;e:Power3.easeOut;"
                     data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                     data-start="1400"  data-splitin="none"  data-splitout="none"  data-responsive_offset="on">
                    <img src="<?=$_layoutParams['public_img']?>slider/slider-1/capas/CHUPACHUPS.png"  style="z-index: 5;"  />
                </div>


            </li>


        </ul>
        <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>	</div>

    </div>
    <div id="crea-aventura-container" >
        <form action="<?=MENU_URL?>libros/" method="GET">
            <div class="container">
                <div class="col-sm-10 col-sm-offset-1">
                    <div class=" text-center" style=" margin-bottom:20px;"><p style="
     font-size: 26px;
    color: #f37558;">Elige la ONG o asociación a la que quieres que donemos el 20% del valor de la compra.</p></div>
                    <div class=" text-center" style=" margin-bottom:20px;"><h5 style="color:orange;font-size:32px;">¡En menos de 1 minuto tendrás tu cuento!</h5></div>
                    <div class=" text-center" style=" margin-bottom:20px;"><h2 class="creatuaventuraslide">CREA TU AVENTURA ÚNICA</h2></div>
                    <div class="col-sm-5"><label>Nombre del niño</label><br /> <input type="text" class="home-name-selector name-changer" name="name"/></div>
                    <div class="col-sm-4 ">
                        <label>Género</label><br />
                        <div class="radio-toolbar clearfix">
                            <div class="col-sm-6 gender1 ">
                                <input type="radio" id="radio1" name="gender" value="1" checked>
                                <label for="radio1">Niño</label>
                            </div>
                            <div class="col-sm-6 gender2">
                                <input type="radio" id="radio2" name="gender" value="2" checked>
                                <label for="radio2">Niña</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3"><br /><button style="    background: orange;
        color: white;
        border: none;
        border-radius: 15px;
        font-family: 'Gloria Hallelujah';
        width: 100%;
        letter-spacing: 1px;
        padding: 16px 20px;
        text-align: center;
        margin-top: 5px;
        line-height: 1.4em;">Elegir Aventura</button></div>
                </div>
            </div>
        </form>
    </div>
</div>

<style>
    #crea-aventura-container {        position: absolute;
        top: 19%;
        left: 0;
        right: 0;
    }}
    .book-title-carousel {font-size:32px; color: #29abe2; font-family:Roboto; margin:15px auto 28px;}
    .creatuaventuraslide {font-family: 'Gloria Hallelujah'; color:#0071bc; font-size:50px;}


    @media screen and (max-width: 986px) {

        #crea-aventura-container {position:absolute; top:21%; left:0;right:0;}
        .creatuaventuraslide {

            font-size: 30px;
        }
    }

    @media screen and (max-width: 768px) {
        #crea-aventura-container {position:relative; top:0; left:0;right:0;}
        .gender1 label, .gender2 label {border-radius:15px; !important}

    }
</style>
<div id="elige-aventura-home" class="section-home">
    <div class="title text-center">
        <h1>ELIGE TU AVENTURA</h1>
    </div>
    <div class="">

        <div class="carousel-3col owl-carousel owl-theme">


            <?php


            foreach($this->books_list as $book) {  ?>
                <div class=" text-center">

                    <div class="book-img">

                        <img src="<?=$_layoutParams['public_img']?>books/<?=$book['slug']?>/<?=$book['main_image']?>" >
                    </div>
                    <h3 class="book-title-carousel"><?=$book['name']?> </h3>
                    <div class="clearfix">
                        <div class="col-sm-8">
                            <a  href="#" class="button-outline-blue">  <img src="<?=$_layoutParams['template_img']?>age_icon.png" style="height:25px; vertical-align: sub; display:inline-block;width:inherit"/>  <?=$book['rango_edad']?> </a>
                        </div>
                        <div class="col-sm-4">
                            <a href="<?=MENU_URL?>libros/ver/<?=$book['slug']?>" class="button-orange">Crear</a>
                        </div>
                    </div>
                </div>
            <?php   } ?>

        </div>
    </div>
</div>

<div class="comofuncionatop"></div>

<div id="como-funciona-home" class="section-home" style="padding-bottom:340px; background-size:cover; background:#f5f5f5 url('<?=$_layoutParams['public_img']?>home/HOME-BG1.jpg') bottom center no-repeat;">
    <div class="container">
        <h2 class="title text-center">¿Cómo Funciona?</h2>

        <br />
       <br />
        <div class="row" style="background: url(<?=$_layoutParams['template_img']?>background-comofunciona.png);    background-repeat: no-repeat;  background-position: center 60px;   background-size: 80%;">
            <div class="col-sm-3 text-center">

                <img style="height:150px; display:block; margin:0 auto 15px;"  src="<?=$_layoutParams['template_img']?>como1.png" >
                <strong>Personaliza tu personaje</strong>
            </div>
            <div class="col-sm-3 text-center" style="padding-top:50px;">

                <img style="height:150px; display:block;margin:0 auto 15px;" src="<?=$_layoutParams['template_img']?>como2.png" >
                <strong>Elige tu aventura</strong>
            </div>
            <div class="col-sm-3 text-center" style="padding-top:50px;">

                <img style="height:150px; display:block;margin:0 auto 15px;" src="<?=$_layoutParams['template_img']?>como3.png" >
                <strong>Añade una  dedicatoria</strong>
            </div>
            <div class="col-sm-3 text-center">

                <img style="height:150px; display:block;margin:0 auto 15px;" src="<?=$_layoutParams['template_img']?>como4.png" >
                <strong>Disfruta de tu libro</strong>
            </div>
        </div>
    </div>
</div>

<?php /*

<section class="gallery">
    <h2 class="title text-center">¡Ellos ya lo disfrutan!</h2>
    <div class="swiper-container swiper-gallery">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            <!-- Slides -->
            <div class="col1 swiper-slide">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img1.jpg" class="size1">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img2.jpg" class="size2">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img3.jpg" class="size3">
            </div>
            <div class="col2 swiper-slide">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img4.jpg" class="size4">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img5.jpg" class="size5">
            </div>
            <div class="col1 swiper-slide">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img6.jpg" class="size1">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img7.jpg" class="size2">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img8.jpg" class="size3">
            </div>
            <div class="col2 swiper-slide">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img9.jpg" class="size4">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img10.jpg" class="size5">
            </div>
            <div class="col1 swiper-slide">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img11.jpg" class="size1">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img12.jpg" class="size2">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img13.jpg" class="size3">
            </div>
            <div class="col2 swiper-slide">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img14.jpg" class="size4">
                <img src="<?=$_layoutParams['public_img']?>disfrutan/img15.jpg" class="size5">
            </div>
        </div>
        <!-- If we need pagination -->
        <div class="swiper-pagination"></div>

        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>

    </div>
</section>
*/ ?>
<style>
    .mb20{margin-bottom:20px;}
</style>
<div id="fundaciones" class="section-home" style="padding-bottom:226px !important; margin-bottom:-150px !important;">
    <div class="container">

        <h2 class="title text-center">Convenios de Colaboración</h2>
        <br />
        <br />
        <div class="row" style="align-content: center;">

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://nuevavida-adopciones.org"><img src="/public/img/fundaciones/comp/nuevavida.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://abejas.org"><img src="/public/img/fundaciones/comp/abejas.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="http://www.acima.es"><img src="/public/img/fundaciones/comp/acima.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://www.fundacionadsis.org"><img src="/public/img/fundaciones/comp/adsis.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://www.fundacioncadete.org"><img src="/public/img/fundaciones/comp/cadete.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="http://fundacioncinde.org"><img src="/public/img/fundaciones/comp/cinde.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="http://www.fundaciondelcorazon.com"><img src="/public/img/fundaciones/comp/corazon.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://diabetesmadrid.org"><img src="/public/img/fundaciones/comp/diabetes-madrid.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://www.fundacionelalto.es"><img src="/public/img/fundaciones/comp/elalto.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a target="_blank" href="https://enfermedades-raras.org/"><img src="/public/img/fundaciones/comp/feder.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="http://www.fundacionisabelgemio.com"> <img src="/public/img/fundaciones/comp/gemio.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://www.amigosdelosmayores.org"> <img src="/public/img/fundaciones/comp/mayores.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="http://www.asociacionpablougarte.es"> <img src="/public/img/fundaciones/comp/pablo-ugarte.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://www.fpdeseo.org"> <img src="/public/img/fundaciones/comp/pequenodeseo.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://www.childheroes.org"><img src="/public/img/fundaciones/comp/childheroes.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://www.tambien.org"> <img src="/public/img/fundaciones/comp/tambien.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://es.theodora.org"> <img src="/public/img/fundaciones/comp/theodora.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="https://zarpasycolmillos.es"><img src="/public/img/fundaciones/comp/zarpas-y-colmillos.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="http://www.downmadrid.org"><img src="/public/img/fundaciones/comp/downmadrid.png" /></a>
            </div>

            <div class="col-sm-2 text-center">
                <a  target="_blank" href="http://www.asion.org"><img src="/public/img/fundaciones/comp/asion.png" /></a>
            </div>


        </div>

    </div>
</div>


<div id="porqueelegir" class="section-home" style="padding-bottom:226px !important; margin-bottom:-150px !important;">
    <div class="container">

        <h2 class="title text-center">¿Por qué elegirnos?</h2>
        <br />
        <br />
        <div class="row">
            <div class="col-sm-3 text-center">

                <img style="height:150px; display:block; margin:0 auto 15px;"  src="<?=$_layoutParams['template_img']?>home/porque1.png" >
                <strong>Cuentos de calidad</strong>
                <br />
                <br />
                <p>
                    Tendrás en tus manos un libro de calidad e interiores a todo color, con unas bellísimas ilustraciones e historias que harán disfrutar a los más pequeños de la casa.
                </p>
            </div>
            <div class="col-sm-3 text-center">

                <img style="height:150px; display:block;margin:0 auto 15px;" src="<?=$_layoutParams['template_img']?>home/porque2.png" >
                <strong>Envío del cuento</strong>
                <br />
                <br />
                <p>
                    Cada libro se crea e imprime de forma personalizada. Todo el proceso puede tardar entre 6 y 10 días.
                </p>
            </div>
            <div class="col-sm-3 text-center">

                <img style="height:150px; display:block;margin:0 auto 15px;" src="<?=$_layoutParams['template_img']?>home/porque3.png" >
                <strong>¡Para todos tus niñ@s!</strong>
                <br />
                <br />
                <p>
                    Son cuentos que abarcan edades de entre 0 y 9 años (aunque lo disfrutará igualmente un adulto). En cada cuento se indica la franja de edad orientativa.
                </p>
            </div>
            <div class="col-sm-3 text-center">

                <img style="height:150px; display:block;margin:0 auto 15px;" src="<?=$_layoutParams['template_img']?>home/porque4.png" >
                <strong>Somos solidarios</strong>
                <br />
                <br />
                <p>
                    El 20% del valor de la compra se donará a la ONG, asociación o fundación que tú elijas.
                </p>
            </div>
        </div>
    </div>
</div>