<?php
//THE PRODUCT
$colors = $this->_data['colors'];
$specials = $this->_data['specials'];
$product = $this->_data['product'];

$langs = $this->_data['langs'];



$errors = @$this->_errors;

if(sizeof(@$errors)>0) {
    echo '<div class="alert alert-danger"><ul>';
    foreach($errors as $error) {
        echo '<li>'.$error.'</li>';
    }
    echo '</ul></div>';
}

if(@$this->_updated>0) {
    echo '<div class="alert alert-success"><p>Se ha actualizado exitosamente.</p></div>';
}
else if (@$this->_updated==-1) {
    echo '<div class="alert alert-warning"><p>No se ha podido actualizar.</p></div>';
}
?>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Dashboard</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="#">Dashboard</a></li>
                </ol>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">

                    <a href="<?=MENU_URL.$this->_controlador?>/add" class="btn btn-primary">AÑADIR NUEVO PRODUCTO</a>
                    <a href="<?=MENU_URL .$this->_controlador?>/add_combination/<?=$product['id']?>" class="btn btn-primary">AÑADIR COMBINACION</a>
                </div>
            </div>
        </div>

        <form id="frmNewNew" class="form-vertical form-bordered" action="<?= BASE_URL.$this->_controlador ?>/action_add_combination" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="d[id]" value="<?= $product['id'] ?>" />

            <div class="row">
                <div class="col-sm-6 text-center"><a href="<?=MENU_URL?>admin_product/edit/<?=$product['id']?>"> <div class="icon-tab"><i class="fa fa-chevron-left"></i> <img src="<?= $_layoutParams['public_img'] ?>products/thumbs/<?=$product['main_img'] ?>" style="width:37px; vertical-align: middle; border:1px solid #c6c6c6; border-radius:7px" /> <?=$product['name']?></div></a></div>
                <div class="col-sm-6"> <button type="submit" class=" btn-primary" style="width: 100%;font-size: 26px; font-weight: 400; border: none; padding: 15px 10px 12px; /* font-weight: bold; */ text-decoration: none !important;"><div class=""><i class="fa fa-save"></i> Guardar</div></button></div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="tab-content">

                        <!-- TAB general -->
                        <div id="tab-general" class="tab-pane active">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="white-box">
                                        <div class="box-title">
                                            <h3>Datos</h3>
                                        </div>


                                        <div class="box-content">
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <h3>Color</h3>
                                                    <select name="d[color]" class="form-control">
                                                        <option value="">Ninguno</option>
                                                        <?php foreach($colors as $color) echo '<option  value="'.$color['id'].'">'.$color['color'].'</option>';?>
                                                    </select>
                                                </div>
                                                <div class="col-sm-4">
                                                    <h3>Acabado Especial</h3>
                                                    <select name="d[special]" class="form-control">
                                                        <option  value="">Ninguno</option>
                                                        <?php foreach($specials as $special) echo '<option  value="'.$special['id'].'">'.$special['acabado'].'</option>';?>
                                                    </select>
                                                </div>
                                                <div class="col-sm-4">
                                                    <h3>Precio PVP</h3>
                                                    <input name="d[price]" type="text" value="" class="form-control" />
                                                </div>
                                            </div>

                                            <div class="row">

                                                <div class="col-sm-4">
                                                    <h3>SKU</h3>
                                                    <input name="d[sku]" type="text" value="" class="form-control" />
                                                </div>
                                                <div class="col-sm-4">
                                                    <h3>Alto (cm)</h3>
                                                    <input name="d[alto]" type="number" value="" class="form-control" />
                                                </div>
                                                <div class="col-sm-4">
                                                    <h3>Ancho (cm)</h3>
                                                    <input name="d[ancho]" type="number" value="" class="form-control" />
                                                </div>
                                            </div>

                                            <br />
                                            <div class="text-right">
                                                <input name="d[id_product]" type="hidden" value="<?=$product['id']?>" class="form-control" />
                                                <input name="d[redirect]" type="hidden" value="<?= BASE_URL.$this->_controlador ?>/edit_combination/" class="form-control" />



                                            </div>
                                        </div>
                                    </div>
                                    <div class="white-box" id="tab-images">
                                        <div class="box-title">
                                            <h3>Imágenes</h3>
                                        </div>
                                        <div class="box-content">

                                            <div class="col-sm-12">
                                                <br />
                                                <br />
                                                <h2 style="font-size:30px">¡Cuando guardes el producto podrás añadirle más imágenes!</h2>
                                            </div>
                                        </div>

                                    </div>






                                </div>
                                <div class="col-sm-6">
                                    <?php include('combinations_table.phtml'); ?>
                                </div>

                            </div>




                        </div>


                    </div>

                </div>
            </div>
        </form>

    </div>
</div>

