
<style>
    .white-box {
        background:white;
        padding:20px;
        margin-bottom:10px;
    }
</style>
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Dashboard
            </h3>
        </div>
    </div>
</div>


<div class="m-content">

    <?php
    //THE PRODUCT


    $product = $this->_data['orders']['data'][0];
    $statuses = $this->_data['statuses'];


    $errors = @$this->_errors;

    if(sizeof(@$errors)>0) {
        echo '<div class="alert alert-danger"><ul>';
        foreach($errors as $error) {
            echo '<li>'.$error.'</li>';
        }
        echo '</ul></div>';
    }

    if(@$this->_updated>0) {
        echo '<div class="alert alert-success"><p>Se ha actualizado exitosamente.</p></div>';
    }
    else if (@$this->_updated==-1) {
        echo '<div class="alert alert-warning"><p>No se ha podido actualizar.</p></div>';
    }


    /*
        echo '<pre>';
        print_r( $product);
        echo '</pre>';
    */
    /*
          echo '<pre>';
              print_r($product);
          echo '</pre>';

                   echo '<pre>';
                     print_r($statuses);
                 echo '</pre>';

             */

    ?>




    <div class="row">
        <div class="col-lg-12">
            <div class="row text-center">
                <div class="col-lg-3">
                    <div class="white-box">
                        <div class="box-title">
                            <h3>PEDIDO<br /><strong>#<?=$product['id']?></strong></h3>
                        </div>

                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="white-box">
                        <div class="box-title">
                            <h3>ESTADO</h3>
                            <td>
                                <form id="frmChangeOrder<?= $product['id'] ?>" class="frmChangeOrder" class="form-vertical form-bordered" action="<?= ADMIN_URL.$this->_controlador ?>/edit_status" method="POST" enctype="multipart/form-data">
                                    <input type="hidden" name="d[id]" value="<?= $product['id'] ?>" />
                                    <select name="d[status_id]" style="text-align:left; width:70%; display: inline-block;" >
                                        <?php
                                        foreach($statuses as $status) {

                                            echo '<option value="'.$status['id'].'"  '.(($product['status']==$status['id']) ? 'selected' : '').' >'.$status['status_name'].'</option>';
                                        }

                                        ?>
                                    </select>
                                    <input type="submit" value="ACTUALIZAR" class="btn btn-sm btn-info" style="width:25%; display: inline-block;";/>
                                </form>
                            </td>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="white-box">
                        <div class="box-title">
                            <h3>FECHA<br /><strong><?=date('d/m/Y H:i:s',$product['date_add'])?></strong></h3>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="white-box">
                        <div class="box-title">
                            <h3>PRODUCTOS<br /><strong><?=sizeof($product['datas'])?></strong></h3>
                        </div>

                    </div>
                </div>
            </div>




            <div class="row">
                <div class="col-lg-6">
                    <div class="white-box">
                        <div class="box-title">
                            <h3>DATOS CLIENTE</h3>
                            <strong>Nombre</strong><p><?= $product['name'] ?></p>
                            <strong>Apellidos</strong><p><?= $product['surnames'] ?></p>
                            <strong>E-Mail</strong><p><?= $product['email'] ?></p>
                        </div>

                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="white-box">
                        <div class="box-title">
                            <h3>DATOS ENVÍO</h3>
                            <div class="row">
                                <div class="col-lg-6">
                                    <strong>Nombre</strong><p><?= $product['envio_nombre'] ?></p>
                                    <strong>Apellidos</strong><p><?= $product['envio_apellidos'] ?></p>
                                    <strong>Direccion</strong><p><?= $product['envio_direccion'] ?></p>
                                    <strong>CP</strong><p><?= $product['envio_cp'] ?></p>
                                </div>
                                <div class="col-lg-6">
                                    <strong>Localidad</strong><p><?= $product['envio_localidad'] ?></p>
                                    <strong>Provincia</strong><p><?= $product['envio_provincia'] ?></p>
                                    <strong>Telefono</strong><p><?= $product['envio_prefijotelefono'] ?> <?= $product['envio_telefono'] ?></p>
                                    <strong>Comentarios</strong><p><?= $product['envio_comentarios'] ?></p>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>




            <!-- --------------------------------- -->
            <!-- --------------------------------- -->
            <!--            EXPORTADOR             -->
            <!-- --------------------------------- -->
            <!-- --------------------------------- -->
            <div class="white-box">
                <div class="box-title">
                    <h3>Borrado pedido</h3>
                </div>
                <div class="box-content">
                    <form id="frmDeleteProduction" class="form-horizontal" action="<?= ADMIN_URL.$this->_controlador?>/action_delete" method="POST" enctype="multipart/form-data">
                        <input type="hidden" name="id" value="<?= $product['id'] ?>"/>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Borrar</button>
                            <a href="<?= ADMIN_URL.$this->_controlador ?>" class="btn">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>


            <div class="white-box">
                <div class="box-title">
                    <h3>PRODUCTOS DEL PEDIDO</h3>
                </div>
                <div class="box-content">
                    <table class=" text-center table table-hover table-nomargin dataTable table-bordered">
                        <thead>
                        <tr>
                            <th width="50" class="text-center">ID</th>
                            <th width="50" class="text-center">Avatar</th>
                            <th  width="80"  class="text-center">Nombre</th>
                            <th width="170"  class="text-center">Dedicatoria</th>
                            <th width="70"  class="text-center">Libro</th>
                            <th width="70"  class="text-center">Formato</th>
                            <th width="70"  class="text-center">LIBRO</th>
                            <th width="70"  class="text-center">PORTADA</th>
                            <th width="70"  class="text-center">EBOOK</th>
                        </tr>
                        </thead>
                        <tbody STYLE="VERTICAL-ALIGN:MIDDLE;">
                        <?php
                        //echo '<pre>';print_r($this->_data);echo '</pre>';
                        if(isset($product['datas']) &&  sizeof($product['datas'])>0)
                            foreach($product['datas'] as $row) {
                                ?>
                                <tr>
                                    <td class="text-center"><?= $row['id'] ?></td>
                                    <td style="text-align:center">
                                        <img style="HEIGHT:30px;" src="<?=BASE_URL?>libros/generateAvatar/?<?=
                                        'book_slug=' . @$row['book_slug'] .
                                        '&gender=' . @$row['gender_id'] .
                                        '&glassesStyle=' . $row['glasses_id'] .
                                        '&skinColor=' . $row['skin_id'] .
                                        '&hairStyle=' . @$row['hair_style_id'] .
                                        '&hairColor=' . @$row['hair_color_id'] .
                                        '&eyesColor=' . @$row['eyes_id'] .
                                        '&clothesColor=' . @$row['clothes_id']
                                        ?>" />
                                    </td>

                                    <td class="text-center"><?= $row['name'] ?></td>
                                    <td class="text-center"><?= $row['dedicatoria_txt'] ?></td>
                                    <td class="text-center"><?= $row['book_name'] ?></td>
                                    <td class="text-center"><?= $row['format_name'] ?> - <?= $row['format_price'] ?>€</td>
                                    <td class="text-center">
                                        <a href="<?= ADMIN_URL.$this->_controlador?>/download_pdf/?id=<?=@$row['id']  ?>&type=tripas" class="btn btn-sm btn-info" style="width:100%; border-radius:0px;" download><i class="fa fa-angle-down"></i>  LIBRO (PDF)</a>
                                        <a href="<?= BASE_URL?>/libros/print_download/?type=tripas&id=<?= md5($row['id'])  ?>&nohex=<?=($row['id'])?>" class="btn btn-sm btn-danger" style="width:100%; border-radius:0px;" download><i class="fa fa-angle-down"></i>  LIBRO (PODI.)</a>


                                    </td>
                                    <td class="text-center">
                                        <a href="<?= ADMIN_URL.$this->_controlador?>/download_pdf/?id=<?=@$row['id']  ?>&type=portada" class="btn btn-sm btn-success" style="width:100%; border-radius:0px;" download><i class="fa fa-angle-down"></i>  PORTADA</a>
                                        <a href="<?= BASE_URL?>/libros/print_download/?type=portada&id=<?= md5($row['id'])?>&nohex=<?=($row['id'])?>" class="btn btn-sm btn-danger" style="width:100%; border-radius:0px;" download><i class="fa fa-angle-down"></i>  PORTADA (PODI.)</a>

                                    </td>
                                    <td class="text-center">
                                        <a href="<?= ADMIN_URL.$this->_controlador?>/download_pdf/?id=<?=@$row['id']  ?>&type=ebook" class="btn btn-sm btn-primary" style="width:100%; border-radius:0px;" download><i class="fa fa-angle-down"></i>  EBOOK</a>
                                    </td>

                                </tr>
                                <?php
                            }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>



        </div>
    </div>
</div>
