
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Dashboard
            </h3>

        </div>
    </div>
</div>


<div class="m-content">

    <!-- END: Subheader -->


        <?php
        $orders = $this->_data['orders'];

        $statuses = $this->_data['statuses'];
        if($orders['error']>0) {
            echo ' <div class="row">
                <div class="col-lg-12">
                    <div class="box box-color alert alert-danger">
                        <h3>Error!</h3>';
            echo (isset($orders['msg']) && $orders['msg']=!'') ? 'Error: '.$orders['msg'] : 'Unknown error.';
            echo '	</div>
                </div>
            </div>';

        }
        if(!isset($orders['data']) || sizeof($orders['data'])==0) {
            echo ' <div class="row">
                <div class="col-lg-12">
                    <div class="box box-color alert alert-warning">
                        <h3>No hay datos.</h3>';
            echo '	</div>
                </div>
            </div>';

        }




        ?>

    <div class="row " style="margin-bottom:20px;">
        <div class="col-sm-12">
            <div class="white-box">


                <a href="<?= ADMIN_URL.$this->_controlador ?>/export" class="btn btn-primary"><i class="fa fa-file-excel-o"></i> DESCARGAR EN EXCEL</a>
            </div>
        </div>
    </div>


        <div class="row">
            <div class="col-sm-12">
                <div class="m-portlet">

                    <div class="m-portlet__head">

                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    Orders
                                </h3>

                            </div>

                        </div>
                    </div>
                    <div class="m-portlet__body">
								
                                <table class=" text-center table table-hover table-nomargin dataTable table-bordered">
                                <thead>
                                    <tr>
                                        <th width="50" class="text-center">ID</th>

                                        <th width="70"  class="text-center">Fecha</th>
                                        <th  width="170"  class="text-center">Usuario</th>
                                        <th  width="170"  class="text-center">ONG</th>
                                        <th  width="60"  class="text-center">Productos</th>
                                        <th  width="80"  class="text-center">Total </th>

                                        <th  width="60"  class="text-center">Coupon Code </th>
                                        <th  width="60"  class="text-center">M. Pago </th>
                                        <th  width="230"  class="text-center">Estado</th>


                                        <th width="200"  class="text-center">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    //echo '<pre>';print_r($orders['data']);echo '</pre>';
                                    if(isset($orders['data']) &&  sizeof($orders['data'])>0)
                                    foreach($orders['data'] as $k => $row) {
                                        $total=0;
                                        foreach($row['datas'] as $product) $total += $product['format_price'];
                                        $products= sizeof($row['datas']);

                                        ?>
                                        <tr>
                                            <td class="text-center"><?= $row['id'] ?></td>
                                            <td><?= date('d/m/Y H:i:s', (!empty($row['date_add'])) ? $row['date_add'] : time());?></td>

                                            <td><?= $row['email'] ?> - <?= $row['name'] ?> <?= $row['surnames'] ?></td>
                                            <td><?= $row['donacion_ong'] ?></td>

                                            <td><?= $products ?></td>
                                            <td><?= (($row['discount_quantity']!='') ? '<del>'.$total.'</del>€<br />'.($total-($total*$row['discount_quantity']/100)) : $total) ?> €</td>
                                            <td><?= $row['discount_name'] ?> <br /> <?= (($row['discount_quantity']!='') ? $row['discount_quantity'].'%' : '') ?></td>
                                            <td><?= $row['metodo_pago'] ?></td>


                                            <td>
                                                <form id="frmChangeOrder<?= $row['id'] ?>" class="frmChangeOrder" class="form-vertical form-bordered" action="<?= ADMIN_URL.$this->_controlador ?>/edit_status" method="POST" enctype="multipart/form-data">
                                                    <input type="hidden" name="d[id]" value="<?= $row['id'] ?>" />
                                                    <select name="d[status_id]" style="text-align:left; width:70%; display: inline-block;" >
                                                        <?php
                                                        foreach($statuses as $status) {

                                                            echo '<option value="'.$status['id'].'"  '.(($row['status']==$status['id']) ? 'selected' : '').' >'.$status['status_name'].'</option>';
                                                        }

                                                        ?>
                                                    </select>
                                                    <input type="submit" value="ACTUALIZAR" class="btn btn-sm btn-info" style="width:25%; display: inline-block;";/>
                                                </form>
                                            </td>




                                            <td  class="text-center">
                                                <a href="<?= ADMIN_URL.$this->_controlador ?>/view/<?= $row['id'] ?>" title="VER" class="btn btn-sm btn-success">&nbsp;<i class="icon fa fa-eye">&nbsp;</i> VER DETALLES</a>
                                                <a href="<?= ADMIN_URL.$this->_controlador ?>/delete/<?= $row['id'] ?>" title="Borrar" class="btn btn-sm btn-danger">&nbsp;<i class="icon fa fa-trash-o">&nbsp;</i> BORRAR</a>
                                            </td>
                                        </tr>
                                    <?php
                                    }
                                    ?>


                                </tbody>
                            </table>

                    </div>
                </div>
            </div>
        </div>
</div>


