<div class="book-heading" style="padding:3vw 0; background-image: url(http://cuentos.dev/public/img/bookbg.jpg);background-position: center;
    background-size: 100%;
    background-repeat: no-repeat;">
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title" style="color:white">Política de Cookies</h1>
    </div>
</div>
<style>
    .mb20 {
        margin-bottom: 20px;
    }

    .overlay {
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
        background: rgba(0, 0, 0, .3);
    }

    .contact ul li a {
        padding: 10px;
        display: block;
        color: #29abe2;
    }

    .social-contact {
        list-style: none
    }

    .social-contact li {
        border-bottom: 0px !important;
        list-style: none;
        display: inline-block;
        margin: 2px 5px;
    }

    .social-contact li a {
        text-decoration: none !important;
        border: 1px dashed #29abe2;
        height: 40px;
        width: 40px;
        text-align: center;
        line-height: 1.3em;
        color: #29abe2;
        font-size: 16px;
        border-radius: 100%;
    }

    .social-contact li a:hover {
        color: #333;
    } .team-member {font-family: 'Gloria Hallelujah'; color:#29abe2; text-align:center; font-size:43Px;}
    .nombre {font-family: 'Gloria Hallelujah'; color:#29abe2; text-align:center; font-size:43Px;}

    .puesto {

        font-family:"Gloria Hallelujah"; font-size:20px; color:#333;}
    .descripcion {margin-top: 20px;}

</style>
<section class="section section-home">
    <div class="container">
        <link href="https://fonts.googleapis.com/css?family=Stalemate" rel="stylesheet">

        <div class="row contact">
            <div class="col-sm-12">
                <p>
                    Al aceptar nuestra política de cookies, usted consiente su uso en este
                    sitio web. A continuación nos gustaría informarle sobre este aspecto:
                </p>
                <p>
                    <strong>¿Qué son las Cookies?</strong>
                </p>
                <p>
                    Una cookie (o galleta informática), es una pequeña información enviada por
                    un sitio web y almacenada en el navegador del usuario, de manera que el
                    sitio web puede consultar la actividad previa del usuario. Digamos que es
                    una forma que tiene el sitio web de recordar las preferencias de cada
                    usuario.
                </p>
                <p>
                    <strong>¿Qué tipos de cookies utiliza esta página web?</strong>
                </p>
                <p>
                    Las cookies son una parte primordial y esencial del correcto funcionamiento
                    de nuestro sitio web. Utilizamos cookies de:
                </p>
                <p>
                    <strong>• Cookies propias</strong>
                    : son aquéllas que se envían al equipo terminal del usuario desde un equipo
                    o dominio gestionado por el propio editor y desde el que se presta el
                    servicio solicitado por el usuario.
                </p>
                <p>
                    <strong>• Cookies de tercero</strong>
                    : son aquéllas que se envían al equipo terminal del usuario desde un equipo
                    o dominio que no es gestionado por el editor, sino por otra entidad que
                    trata los datos obtenidos través de las cookies.
                </p>
                <p>
                    <strong>• Cookies de sesión</strong>
                    : son un tipo de cookies diseñadas para recabar y almacenar datos mientras
                    el usuario accede a una página web.
                </p>
                <p>
                    <strong>• Cookies persistentes</strong>
                    : son un tipo de cookies en el que los datos siguen almacenados en el
                    terminal y pueden ser accedidos y tratados durante un periodo definido por
                    el responsable de la cookie, y que puede ir de unos minutos a varios años.
                </p>
                <p>
                    <strong>• Cookies de análisis</strong>
                    : son aquéllas que bien tratadas por nosotros o por terceros, nos permiten
                    cuantificar el número de usuarios y así realizar la medición y análisis
                    estadístico de la utilización que hacen los usuarios del servicio ofertado.
                    Para ello se analiza su navegación en nuestra página web con el fin de
                    mejorar la oferta de productos o servicios que le ofrecemos.
                </p>
                <p>
                    <strong>• Cookies publicitarias</strong>
                    : son aquellas que permiten la gestión, de la forma más eficaz posible, de
                    los espacios publicitarios que, en su caso, el editor haya incluido en una
                    página web, aplicación o plataforma desde la que presta el servicio
                    solicitado en base a criterios como el contenido editado o la frecuencia en
                    la que se muestran los anuncios.
                </p>
                <p>
                    <strong>• Cookies de publicidad comportamental</strong>
                    : son aquéllas que permiten la gestión, de la forma más eficaz posible, de
                    los espacios publicitarios que, en su caso, el editor haya incluido en una
                    página web, aplicación o plataforma desde la que presta el servicio
                    solicitado. Estas cookies almacenan información del comportamiento de los
                    usuarios obtenida a través de la observación continuada de sus hábitos de
                    navegación, lo que permite desarrollar un perfil específico para mostrar
                    publicidad en función del mismo.
                </p>
                <p>
                    Asimismo es posible que al visitar alguna página web o al abrir algún email
                    donde se publique algún anuncio o alguna promoción sobre nuestros productos
                    o servicios se instale en tu navegador alguna cookie que nos sirve para
                    mostrarte posteriormente publicidad relacionada con la búsqueda que hayas
                    realizado, desarrollar un control de nuestros anuncios en relación, por
                    ejemplo, con el número de veces que son vistos, dónde aparecen, a qué hora
                    se ven, etc.
                </p>
                <p>
                    Mi Cuento Mágico no usa las cookies para almacenar información personal,
                    tampoco para dirigir publicidad nuestra.
                </p>
                <p>
                    <strong>¿Quién usa entonces las cookies de Mi Cuento Mágico?</strong>
                </p>
                <p>
                    La información que se almacena en la cookies es usada exclusivamente por
                    nosotros. A excepción de Google Analytics, que es usada y gestionada por
                    Google y Mi Cuento Mágico con fines estadísticos.
                </p>
                <p>
                    Es posible que al navegar por otras webs se publiciten anuncios de nuestros
                    productos. La visualización de estos es gestionada a través de datos
                    obtenidos mediante cookies a las que Mi Cuento Mágico tiene acceso.
                </p>
                <p>
                    Todas las cookies son anónimas y su finalidad es el seguimiento de la
                    navegación y sus gustos para poder mostrarles una mejor experiencia de
                    usuario y una publicidad acorde a sus gustos.
                </p>
                <p>
                    <strong>¿Cómo desactivar las cookies en su terminal?</strong>
                </p>
                <p>
                    Digamos que puede hacerlo cuando quiera. Sin embargo, si usted selecciona
                    esta configuración tendrá dificultad para acceder a ciertas partes de
                    nuestra web, tener una navegación menos eficaz e incluso tener dificultad
                    para realizar un pedido de forma correcta.
                </p>
                <p>
                    Puede bloquear, restringir, borrar o establecer las cookies que quiere que
                    funcionen en Mi Cuento Mágico mediante la configuración del navegador:
                </p>
                <p>
                    <strong>• Si usa </strong>
                    <a
                            href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we"
                            target="_blank"
                            title="Configuración del Navegador Firefox"
                    >
                        <strong>Firefox</strong>
                    </a>
                </p>
                <p>
                    <strong>• Si usa </strong>
                    <a
                            href="http://support.google.com/chrome/bin/answer.py?hl=es&amp;answer=95647"
                            target="_blank"
                            title="Configuración del navegador Chrome"
                    >
                        <strong>Chrome</strong>
                    </a>
                </p>
                <p>
                    <strong>• Si usa </strong>
                    <a
                            href="http://windows.microsoft.com/es-es/internet-explorer/delete-manage-cookies#ie=ie-11"
                            target="_blank"
                            title="Configuración del Navegador IE"
                    >
                        <strong>Internet Explorer</strong>
                    </a>
                </p>
                <p>
                    <strong>• Si usa </strong>
                    <a
                            href="https://support.apple.com/es-es/HT201265"
                            target="_blank"
                            title="Configuración del Navegador Safari"
                    >
                        <strong>Safari</strong>
                    </a>
                </p>
                <p>
                    <strong>• Si usa </strong>
                    <a
                            href="http://help.opera.com/Windows/11.50/es-ES/cookies.html"
                            target="_blank"
                            title="Configuración del Navegador Opera"
                    >
                        <strong>Opera</strong>
                    </a>
                </p>
            </div>


        </div>




</section>