
					<?php

                        //THE PRODUCT
						$programa = $this->_data['product']['data'][0];

						//FILTERS
						$filters = $this->_data['filters']['data'];





					
						$errors = @$this->_errors; 
						
						if(sizeof(@$errors)>0) {
							echo '<div class="alert alert-danger"><ul>';
							foreach($errors as $error) {
								echo '<li>'.$error.'</li>';
							}
							echo '</ul></div>';
						}
						
						if(@$this->_updated>0) {
							echo '<div class="alert alert-success"><p>Se ha actualizado exitosamente.</p></div>';
						}
						else if (@$this->_updated==-1) {
							echo '<div class="alert alert-warning"><p>No se ha podido actualizar.</p></div>';
						}
					?>
					
					
				
				<form id="frmNewNew" class="form-vertical form-bordered" action="<?= BASE_URL.$this->_controlador ?>/action_edit" method="POST" enctype="multipart/form-data">
					<input type="hidden" name="d[id]" value="<?= $programa['id'] ?>" />
					<div class="row">
						
						
						<div class="col-lg-9">

                            <div class="box box-color box-bordered lightgrey">
                            <div class="box-title">
                                <ul class="tabs tabs-left">
							<?php 
								foreach($langs as $k => $v) {
                                    ?>

                                    <li class="<?= (current($v)==1) ? 'active': ''; ?> <?= current($v); ?>">
                                        <a href="#lang-<?= $v['tagname'] ?>" data-toggle="tab"> <?php echo $v['name'] ?></a>
                                    </li>


                                    <?php
                                }
                            ?>
                                </ul>

                            </div>
                            <div class="box-content">
                                <div class="tab-content">
                            <?php

								foreach($langs as $k => $v) {
							?>
                                <div class="tab-pane <?= (current($v)==1) ? 'active': ''; ?>" id="lang-<?=$v['tagname']; ?>">


								
									<?php 	
									$errors = @$this->_errors; 
									
									if(sizeof(@$errors)>0) {
										echo '<div class="alert alert-danger"><ul>';
										foreach($errors as $error) {
											echo '<li>'.$error.'</li>';
										}
										echo '</ul></div>';
									}
									
									?>

										<?php	

											$langid =  strtoupper($v['tagname']);
											$langidl =  strtolower($v['tagname']);

												?>
                                            <div class="control-group mt10">
                                                <label for="titulo" class="control-label">Título</label>
                                                <div class="controls">
                                                    <input id="titulo" type="text" class="form-control" name="d[<?= $langidl ?>][name]" value="<?= @$programa['langs'][$langidl]['name'] ?>" required />

                                                </div>
											</div>

                                    <div class="control-group">
                                        <label for="slug" class="control-label">Slug</label>
                                        <div class="controls">
                                            <input id="slug" type="text" class="form-control" name="d[<?= $langidl ?>][slug]"  value="<?= @$programa['langs'][$langidl]['slug'] ?>" required />
                                            <span class="help-block">
												El slug es lo que se refleja en la URL.<br />
												http://dominio.com/noticias/<strong>esto-es-el-slug</strong><br />
												El slug no puede contener caracteres extraños, mayusculas ni espacios.
											</span>
                                        </div>
                                    </div>
                                        <div class="row">
                                            <div class="col-sm-12">

                                                <div class="control-group mt10">
                                                    <label for="descripcion" class="control-label">Descripción</label>
                                                    <div class="controls">
                                                        <textarea rows="10"  style="width:100%;" class="ckeditor" cols="80" id="<?= $langidl ?>-long_desc"  name="d[<?= $langidl ?>][long_desc]"><?= html_entity_decode(@$programa['langs'][$langidl]['long_desc'])?></textarea>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-12">
                                                <div class="control-group mt10">
                                                    <label for="descripcion_corta" class="control-label">Descripción corta</label>
                                                    <div class="controls">
                                                        <textarea rows="10" class="" cols="80"  style="width:100%" id="<?= $langidl ?>-short_desc"  name="d[<?= $langidl ?>][short_desc]" required><?= html_entity_decode(@$programa['langs'][$langidl]['short_desc'])?></textarea>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                </div>


							<?php } ?>
                                </div>
                            </div>
                            </div>

								
						</div>
						<div class="col-lg-3" id="">
						
						
							<div class="box box-color box-bordered lightgrey">
								<div class="box-title"><h3>Datos de la publicación</h3></div>
								<div class="box-content">
								
									<div class="row mb20">
										<div class="col-sm-6">
											<div class="control-group">
												<label for="visible" class="control-label">Visible</label>
												<div class="controls">
													<input class="switcher" type="checkbox"  <?= (@$programa['visible']>0) ? 'checked' :''; ?> name="d[visible]">
												
												</div>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="control-group">
												<label for="destacada" class="control-label">Destacada</label>
												<div class="controls">
													<input class="switcher" type="checkbox"  <?= (@$programa['featured']>0) ? 'checked' :''; ?> name="d[featured]">
												
												</div>
											</div>
										</div>
									</div>


                                    <div class="row">

                                        <div class="col-sm-12">

                                            <div class="control-group">
                                                <label for="file" class="control-label">Miniatura (612px * 700px)</label>
                                                <div class="controls">

                                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 280px; height: 150px;">
                                                            <img src="<?= $_layoutParams['public_img'] ?>products/thumbs/<?=$programa['main_img'] ?>" />
                                                        </div>
                                                        <div>
                                                                        <span class="btn btn-default btn-file">
                                                                            <span class="fileinput-new">Seleccionar</span>
                                                                        <span class="fileinput-exists">Cambiar</span>
                                                                        <input type="file" name="miniatura">
                                                                        </span>
                                                            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="row">
                                    <?php foreach($filters as $filter) {
                                        ?>
                                        <div class="col-sm-6">
                                            <div class="control-group">
                                                <label for="<?= $filter['key'] ?>" class="control-label"><?= $filter['name'] ?></label>
                                                <div class="controls">
                                                    <select id="<?= $filter['key'] ?>"  type="text" class="form-control" name="d[<?= $filter['key'] ?>][]" >
                                                        <?php foreach($filter['values'] as $value) {
                                                            echo '<option value="'.$value['id'].'" '.((in_array($value['id'],$programa['cates']))?'selected':'').'>'.$value['name'].'</option>';
                                                        }
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <?php
                                    }
                                    ?>


                                        <div class="col-sm-6">
                                            <div class="control-group">
                                                <label for="categd" class="control-label">Precio</label>
                                                <div class="controls">
                                                   <input type="text" id="precio-input" class="form-control" name="d[precio]" value="<?php echo @$programa['precio']?>" />
                                                </div>
                                            </div>
                                        </div>

                                    </div>

									
									<div class="form-actions">
										<input type="hidden" name="c[id]" value="<?= $programa["id"] ?>" />
										<button type="submit" class="btn btn-primary">Guardar</button>
										<a href="<?= BASE_URL.$this->_controlador ?>/lista" class="btn">Cancelar</a>
									</div>
								
								</div>
							</div>
						</div>
						
					</div>
				</form>
		

