<div class="index-header">
	<hgroup class="article__headline">
		<h2 class="headline__secondary" ><span class="first-letter">Cierra Sesión</h2>
	</hgroup>					
</div>

<style>
	.index-header {text-align:center; padding:100px 0; background:url(http://luesmavega.eu/wp-content/uploads/2014/06/cabecera-2048x1365.jpg);}
    .mb20 {margin-bottom:20px;}
    select {background:#eee;color:#444;border:none;border-radius:0px;}

    .submit{
        border: 1px solid #444;
        padding: 6px 25px;
        /* margin-top: 10px; */
        text-transform: uppercase;
        font-size: 18px;
        margin: 2px auto;
        display: block;
        border-radius: 15px;
        background: white;

    }

    .range{
        display: inline-block !important;
        width: 80% !important;
        top: 6px;
        float: right;
        position: relative;
        margin-left: 10px;}

    .color-picker {
        margin: 0;
        padding: 0;
        display: inline-block;
        top: 7px;
        position: relative;
        margin-left: 10px;
    }
    .color-picker li {
        display: inline-block;
        margin: 2px 3px;
        border-radius: 100%;
        width: 26px;
        height: 26px;
    }
    .color-picker li.red {background-color:red;}
    .color-picker li.green {background-color:green;}
    .color-picker li.yellow {background-color:yellow;}
    .color-picker li.orange {background-color:orange;}
    .color-picker li.black {background-color:black;}

    label {display:inline-block}


    .form-control-feedback {
        position: absolute;
        top: 11px;
        right: 12px;
        z-index: 2;
        display: block;
        width: 34px;
        height: 34px;
        line-height: 34px;
        text-align: center;
        pointer-events: none;
    }
    .form-control {
        background: #fff;
        border-radius: 40px;
        border: 1px solid #eee;
        height:56px;
        border: 1px solid #ccc !important;
        padding-left:24px !important;
    }

    #btn_submit {border: 1px solid #337ab7;
        color: #337ab7;
        background: none;
        border-radius: 35px;
        font-size: 15px;
        text-transform: uppercase;
        letter-spacing: 2px;
    }

    #btn_submit:hover {
        background: #337ab7;
        color:white;
    }

    #btn_remember {    display: block;
        border-radius: 35px;
        border: 1px solid #888;
        color: #888;
        background: transparent;
    }

    #btn_register {
        display: block;
        border-radius: 35px;
        background: #337ab7;
        border: 1px solid #337ab7;
        /* margin: -3px !important; */

    }
</style>

<div class="container">
    <!-- start section filter -->
   <div class="row">

       <div style="background:#Fafafa; border-radius:30px;padding:30px;color:#333;margin:80px 0 80px;">


           <form method="POST" action="<?= BASE_URL ?>logout/makeLogout" accept-charset="UTF-8" role="form" class="login-form">


               <div class="row">

                   <div class="col-sm-12">
                       <button id="btn_submit" type="submit" class="btn btn-primary btn-block btn-flat">Cerrar Sesión</button>
                   </div><!-- /.col -->
               </div>
           </form>

       </div>

    </div> <!-- end row -->
</div> <!-- end container -->