<?php
$book = $this->book;

?>

<div class="book-heading"
     style="padding: 70px 0 160px; background-image: url(<?php echo $_layoutParams['public_img'] ?>books/<?php echo $book['slug'] ?>/heading.jpg);background-position: center; background-size: cover; background-repeat: no-repeat;">
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title-heading" style="color:white"><?php echo $book['name'] ?></h1>
    </div>

</div>

<div class="container">
    <div class="row">
        <div class="col-sm-4" style="margin-top:-80px">
            <aside class=" z-index99 relative" style="padding:25px;">
                <h2 class="acta_bold size26 column">Sinopsis</h2>
                <div class="mt-px20 inline pr-px50">
                    <p class="proxima size18 line-height130 column"><?php echo $book['description'] ?></p>
                </div>
                <hr/>
                <h4>Precios</h4>
                <ul>
                    <?php foreach($book['formatos'] as $formato) echo' <li style="border-bottom:1px dotted #ccc;">
                    '.$formato['nombre'].' 
                    <span  class="pull-right">'.number_format(doubleval($formato['precio']),2).'€</span>
                    </li>';  ?>
                </ul>
                <hr/>
                <h4>Info Adicional</h4>
                <ul>
                    <li style="border-bottom:1px dotted #ccc;">Escritor <span class="pull-right"><?php echo $book['redaccion_por'] ?></span></li>
                    <li style="border-bottom:1px dotted #ccc;">Ilustrador <span class="pull-right"><?php echo $book['ilustracion_por'] ?></span></li>
                </ul>
            </aside>
        </div>

        <div class="col-sm-8 text-center "
             style="margin-top:20px; background: rgba(255,255,255,.95); border-radius:40px;padding:30px">
            <div class="book-img" style="  margin-top:-120px; margin-bottom:40px;"><img   src="<?php echo $_layoutParams['public_img'] ?>books/<?php echo $book['slug'] ?>/<?php echo $book['main_image'] ?>" style="    max-width: 100%; "></div>
            <?php  if($book['available']>0){ ?>
                <div class="row" style=" margin-bottom:60px;">
                    <div class="col-sm-6 ">
                        <a class="btn btn-crear-cuento" href="<?php echo MENU_URL ?>libros/personalizar/<?php echo $book['slug'] ?>/?<?php if (isset($_GET['gender']) && $_GET['gender'] != '') echo 'gender=' . $_GET['gender'] ?><?php if (isset($_GET['name']) && $_GET['name'] != '') echo '&name=' . $_GET['name'] ?>"  >PERSONALIZAR <i class="fa fa-chevron-right"></i></a>
                    </div>
                    <div class="col-sm-6 ">
                        <a href="#elige-aventura-home" class="btn btn-outline-orange">ESCOGER OTRO <i class="fa fa-chevron-right"></i></a>
                    </div>
                </div>
            <?php

            }else
            {
                ?>
               <div class="alert alert-info">Próximamente disponible...</div>
                <?php
            }?>

            <div class="info-adicional row">
                <div class="block proxima  text-center col-sm-6" >
                    <div style=" border: 1px dashed #0a7ae2; border-radius:30px;  margin-bottom:20px; padding:20px;">
                        <div style="margin-bottom: 20px;  text-align:center; display:block"><img src="<?php echo $_layoutParams['public_img'] ?>star-flat.png"  style="vertical-align:bottom; display:inline-block; height:35px"/>  </div>
                        <p><strong>Valores</strong></p>
                        <p><?php echo $book['valores'] ?></p>
                    </div>
                </div>
                <div class="block proxima text-center  col-sm-6" >
                    <div style=" border: 1px dashed #0a7ae2; border-radius:30px; margin-bottom:20px; padding:20px;">
                        <div style=" margin-bottom: 20px; display:block; text-align:center;"> <img src="<?php echo $_layoutParams['template_img'] ?>age_icon.png" style="vertical-align:bottom;  display:inline-block;  height:35px"/>  </div>
                        <p><strong>Edades</strong></p>
                        <p><?php echo $book['rango_edad'] ?></p>
                    </div>
                </div>

            </div>

            <br/>
            <br/>
            <hr/>

        </div>

    </div>
</div>


<style>
    .info-adicional {
        font-family: Roboto;
    }
</style>


<div id="elige-aventura-home" class="section-home">
    <div class="title text-center">
        <h1>OTRAS AVENTURAS</h1>
    </div>
    <div class="">

        <div class="carousel-3col owl-carousel owl-theme">


            <?php

            foreach ($this->books_list as $book) { ?>
                <div class=" text-center">
                    <div class="book-img">
                        <img src="<?php echo $_layoutParams['public_img'] ?>books/<?php echo $book['slug'] ?>/<?php echo $book['main_image'] ?>">
                    </div>
                    <h3 class="book-title" style="font-size:20px;"><?php echo $book['name'] ?> </h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="#" class="button-outline-blue">
                                <img src="<?php echo $_layoutParams['template_img'] ?>age_icon.png" style="    vertical-align: sub;
    height: 24px;
    width: inherit;
    display: inline-block;"/> <?php echo $book['rango_edad'] ?>
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <a href="<?php echo MENU_URL ?>libros/ver/<?php echo $book['slug'] ?>/<?php if (isset($_GET['gender'])) echo 'gender=' . $_GET['gender'] ?><?php if (isset($_GET['name'])) echo 'name=' . $_GET['name'] ?>"
                               class="button-orange">Crear</a>
                        </div>
                    </div>
                </div>
                <?php
            } ?>

        </div>
    </div>
</div>

