<div class="page-heading" >
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title-heading" style="color:white">Equipo</h1>
    </div>
</div>
<style>.team-member {margin-bottom:80px;}</style>
<section class="section section-home" style="margin-bottom:-70px;"">
    <div class="container">

        <div class="row contact">
            <div class="col-sm-12">
                <h1><strong>Fundadores</strong></h1>


                <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img'] ?>nosotros/trazo-nos.png" style="width:300px;"/></div>


                <div class="row team-member">

                    <div class="col-sm-4">
                        <img src="<?= $_layoutParams['public_img']?>team/gloria.png" />
                    </div>
                    <div class="col-sm-8">
                        <h3>Gloria María Vélez</h3>
                        <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img'] ?>nosotros/trazo-nos.png" style="width:300px;"/></div>
                        <p style="line-height:1.4em; color: #999999; font-size:16px;">
                            ESCRITORA / ADMINISTRADORA DE EMPRESAS / COFUNDADORA DE MI CUENTO MAGICO
                            <br/>
                            <br/>
                            Soy colombiana con nacionalidad española, e hija de padres educadores. He trabajado más de 10 años en puestos administrativos en diversos sectores empresariales en Colombia y España.<br />
                            Me considero una persona entregada por lo que hace, alegre, soñadora y creativa. Me encanta escribir, aunque con “Mi cuento mágico” es la primera vez que lo hago de forma profesional.<br />
                            Mis inicios como escritora comenzaron a los nueve años cuando creaba algo parecido a los comics a mi hermana pequeña.<br />
                            Las historias que escribía quedaron archivadas y poco a poco mi sueño de escritora fue pasando a un segundo plano para dedicarme a los estudios y posteriormente a trabajar como administrativa. Durante este tiempo aprendí mucho sobre diferentes empresas que me han ayudado en mi nueva aventura empresarial.<br />
                            Cuando nació mi hijo hace ya casi tres años regresaron de nuevo las ansias de volver a crear y escribir nuevas historias retomando nuevamente el sueño que comenzó desde niña.<br />
                            <br /><br />
                            Mis primeros cuentos de forma profesional han sido para “Mi cuento mágico” y son: “Jugando en la granja”, “Buscando el juguete perdido” y “El juego de troll”.

                        </p>

                    </div>
                </div>





                <div class="row team-member">

                    <div class="col-sm-4 ">
                        <img src="<?= $_layoutParams['public_img']?>team/danielvelasco.png" />
                    </div>
                    <div class="col-sm-8">
                        <h3>Daniel Velasco</h3>
                        <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img'] ?>nosotros/trazo-nos.png" style="width:300px;"/></div>
                        <p style="line-height:1.4em; color: #999999; font-size:16px;">
                            Administrativo - Cofundador de Mi cuento mágico
                            <br />
                            <br />
                            Nací en Valladolid en 1980 pero crecí en Medina del Campo hasta los 20 años.<br /><br />
                            Desde entonces he vivido en Madrid y Colombia. He trabajado como administrativo y gestor telefónico durante 15 años.<br /><br />
                            Durante mi estancia en Colombia comenzó mi deseo de tener mi propia empresa, cosa que pude lograr allí. Desde pequeño siempre me interesó el mundo de la informática y más de mayor el mundo virtual y las redes sociales.
                            <br /><br />
                            Hasta que un día surgió la idea del actual proyecto juntando las experiencias laborales y deseos que tuve desde pequeño, junto a la pasión por la escritura de mi mujer.

                        </p>

                    </div>
                </div>
        </div>
    </div>
    </div>

<div style="background: #f6f6f6; padding-top:60px; padding-bottom:180px; margin-bottom: -120px;">

    <div class="container">

    <h1><strong>Ilustradores</strong></h1>


                <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img'] ?>nosotros/trazo-nos.png"  style="width:300px;"/></div>


                <div class="row team-member">

                    <div class="col-sm-4 text-center">
                        <img src="<?= $_layoutParams['public_img']?>ilustradores/danielberea.png" style="margin-top:40px;    width: 250px;"  />
                    </div>
                    <div class="col-sm-8">
                        <h3>Daniel Berea</h3>
                        <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img'] ?>nosotros/trazo-nos.png" style="width:300px;"/></div>
                        <p style="line-height:1.4em; color: #999999; font-size:16px;">
                            <strong>DIRECTOR Y FUNDADOR DE <a href="https://acornstudio.es" >ACORN</a> | ILUSTADOR | DIRECTOR DE ARTE </strong>
                            <br/>
                            <br/>
                            Director de arte, ilustrador desde pequeño y cofundador de la agencia digital Acorn,<br >
                            Mi ilusión desde niño era el arte, la ilustración, la creatividad, generar imágenes que impacten, viñetas entretenidas, pequeños cuentos…<br />
                            lo que me llevó a realizar la carrera de Bellas Artes en Salamanca, especializandome en pintura y diseño, posteriormente realicé un Master en la escuela Elisava de Barcelona y tras una etapa en 3 agencias de publicidad como diseñador y como director de arte decidí emprender mi propio camino junto a mi socio, montando Acorn Digital Agency en la que ya llevamos 4 años trabajando para marcas como Mercedes, Mango, La Caixa, Barça, Atlético de Madrid....<br /><br />
                            En mi cuento mágico vi la posibilidad de representar una de mis grandes ilusiones de niño, crear un cuento personalizado, tengo que dar gracias a Daniel y Gloria por confiar en nosotros para este proceso de diseño, programación e ilustración del proyecto Mi Cuento Mágico.<br /><br />
                            Espero que podáis disfrutar de estos libros tanto como nosotros hemos disfrutando haciendo cada viñeta en donde tú serás el protagonista.


                        </p>

                    </div>
                </div>





                <div class="row team-member">

                    <div class="col-sm-4 text-center">
                        <img src="<?= $_layoutParams['public_img']?>ilustradores/yolanda.png" style="margin-top:40px;    width: 250px;"  />
                    </div>
                    <div class="col-sm-8">
                        <h3>Yolanda Cabrera</h3>
                        <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img'] ?>nosotros/trazo-nos.png" style="width:300px;"/></div>
                        <p style="line-height:1.4em; color: #999999; font-size:16px;">
                            Soy una ilustradora freelance y diseñadora gráfica afincada en Extremadura. Tras
                            licenciarme en Bellas Artes (Diseño Grafico y Grabado) por la Universidad de Sevilla, me
                            dediqué a la docencia y al mundo de la Ilustración.
                            <br />
                            He ilustrado en España libros infantiles para Entrelineas Editores, Babidi-bú,
                            Vivelibro y realizado las ilustraciones de los libros de texto de editoriales
                            colombianas como Iniciar Ediciones y Editorial Huellas.
                            <br />
                            Prefiero progresar paso a paso, sin prisas y sin hacer ruido, y es por eso que suelo
                            elegir el camino menos transitado, donde a menudo me encuentro con cosas
                            inesperadas e interesantes.
                            <br />
                            Vivo donde se escuchan pájaros al despertar y sueño en voz alta. La luna llena me
                            causa respeto y su acompañante, el hombre lobo, no me gusta nada.
                            <br />
                            Cuelgo mi trabajo diario en las redes sociales. Disfruto teniendo un contacto
                            cercano con mis seguidor@s y agradezco día a día sus comentarios.
                            Ahora tengo un proyecto que me acercará aún más a ti, ilustrar tu propia historia
                            junto a Mi cuento Mágico.

                        </p>

                    </div>
                </div>


                <div class="row team-member">

                    <div class="col-sm-4 text-center">
                        <img src="<?= $_layoutParams['public_img']?>ilustradores/carolina.png" style="margin-top:40px;    width: 250px;"  />
                    </div>
                    <div class="col-sm-8">
                        <h3>Carolina Valtuille</h3>
                        <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img'] ?>nosotros/trazo-nos.png" style="width:300px;"/></div>
                        <p style="line-height:1.4em; color: #999999; font-size:16px;">
                            Nací en un pueblo de Rusia donde comenzó a aflorar mi pasión por el dibujo. A los diez años me trasladé a España y unos años más tarde me di cuenta de que la ilustración era a lo que quería dedicarme. Conforme fueron pasando los años, me he ido formando y adquiriendo experiencia en distintas técnicas y estilos, dando prioridad a la ilustración infantil y juvenil.
                            <br /><br />
                            He colaborado en publicaciones como "Prisma y la felicidad", "The
                            adventures of Blue Parrot", "Felix, The hedgehog" y cuentos de distintas
                            temáticas e ilustraciones para varias aplicaciones educativas. Por otro
                            lado he creado e ilustrado mis propios cuentos: "El lorito de colores",
                            "El gatito y el dragón", entre otros. Mi proyecto más reciente son las
                            ilustraciones para "Mi cuento mágico".



                        </p>

                    </div>
                </div>





            </div>

        </div>
        </div>


</section>
