<div class="page-heading" >
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title-heading" style="color:white">Nosotros</h1>
    </div>
</div>

<section class="section " style="background:url('<?=$_layoutParams['public_img']?>backgroundgif.gif') bottom center no-repeat; padding-bottom:310px; background-size: 100%;">
    <div class="container">
        <link href="https://fonts.googleapis.com/css?family=Stalemate" rel="stylesheet">

        <div class="row contact">
            <div class="col-sm-12">
                <h4>QUIÉNES SOMOS</h4>
                <div style="margin:10px 0;"><img src="<?= $_layoutParams['public_img']?>nosotros/trazo-nos.png" style="width:300px;" /></div>

                <p style="line-height:1.4em; color: #999999; font-size:18px;">

                        Esta historia nace hace varios años, cuando nací yo, Alejandro (o Alejito como me decían de bebé). Según dicen mis papis, mi nacimiento les recordó que somos los protagonistas de nuestra propia historia y que podemos hacer realidad los sueños.
                        <br />
                       <br />
                        Cuando fui a cumplir mi 2º año de nacido, a mi papá se le ocurrió comprarme un cuento personalizado y me gustó mucho, porque me veía reflejado en él, con mis ojos castaños, mi pelo negro, mi camiseta azul que tanto me gustaba. Y desde entonces todas las noches antes de irme a dormir les pedía que me lo leyeran, aunque reconozco que al comienzo sólo me fijaba en los dibujos y colores, pero con el paso del tiempo fui comenzando a señalar cosas que veía en el cuento y a aprender a decir alguna palabra.

                </p>
                <br />
                <div class="col-sm-6">
                    <div class="team-member row">
                        <div class="col-sm-6">
                            <img src="<?= $_layoutParams['public_img']?>team/gloria.png" />
                        </div>
                        <div class="col-sm-6">
                            <div class="nombre">
                                <strong style="font-family: 'Gloria Hallelujah'; color:#29abe2; font-size:23px; line-height: 1.5em;">Gloria María Vélez</strong>

                            </div>
                            <div class="puesto">
                                <small>Co-Fundador</small>
                            </div>
                            <div class="bop">
                                <a href="<?=MENU_URL?>nosotros/equipo"  class="btn-outline-orange ">VER BIOGRAFÍA</a>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="team-member row">
                        <div class="col-sm-6">
                            <img src="<?= $_layoutParams['public_img']?>team/danielvelasco.png" />
                        </div>
                        <div class="col-sm-6">
                            <div class="nombre">
                                <strong style="font-family: 'Gloria Hallelujah';  color:#29abe2; font-size:23px; line-height: 1.5em;">Daniel Velasco</strong>

                            </div>
                            <div class="puesto">
                                <small>Co-Fundador</small>
                            </div>
                            <div class="bop">
                                <a href="<?=MENU_URL?>nosotros/equipo"  class="btn-outline-orange ">VER BIOGRAFÍA</a>

                            </div>
                        </div>

                    </div>
                </div>

                <br />
                <p style="line-height:1.4em; color: #999999; font-size:18px;">
                         Mis papis siempre han sido muy cariñosos conmigo y desde que nací han estado muy pendientes de que sea feliz. Siempre me cantaban (incluso cuando aún estaba en la barriguita de mi mamá) y me leían cuentos todos los días. A mí me gustaban que me prestaran tanta atención, que me mostraran tanto cariño, afecto y amor.
                        <br />
                        <br />
                        Y mis papis, viendo lo original y divertido que era, quisieron emprender un nuevo sueño en sus vidas: a mi mamá siempre la había gustado escribir y a mi papá el mundo de la informática. Y uniendo esas dos pasiones fue como nació el proyecto de Mi cuento mágico.
                        <br />
                        <br />
                        Espero que los niños y niñas que lean estas historias disfruten tanto como lo hice y sigo haciendo, y descubran lo fantástico y lo mágico que esconden los cuentos.

                </p><br />

                <p><strong style="color: #999999; font-size:20px; line-height: 1.3em; font-weight:bold; ">“Mi cuento mágico”, un lugar donde tú eres el protagonista</strong></p>
                <a href="<?=MENU_URL?>libros" class="pull-right btn btn-orange" >CREA TU CUENTO!</a>
            </div>

        </div>




</section>

<section class="section home-section" style="padding-top:50px; padding-bottom:140px;">

    <div clasS="container">
        <div class="text-center " stye="margin-top:40px;">
            <h3  style="color: #29abe2; margin-bottom:0; font-weight: 600; font-family: 'Gloria Hallelujah'; ">Nuestros</h3>
            <h1  class="title"  style="margin-top:0; color: #29abe2; font-weight: 600; font-family: 'Gloria Hallelujah'; ">Ilustradores</h1>
         </div>


        <div clasS="row">
            <div class="col-sm-4">
                <div class="ilustrador">
                    <img src="<?= $_layoutParams['public_img']?>ilustradores/danielberea.png"  style="    width: 250px;" />
                    <div class="nombre">
                        <strong>Daniel Berea</strong>
                    </div>
                    <div class="puesto">
                        <small>Director de Acorn</small>
                    </div>

                    <div class="bop  mt-20">
                        <a href="<?=MENU_URL?>nosotros/equipo"  class="btn-outline-blue" >VER BIOGRAFÍA</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="ilustrador">
                    <img src="<?= $_layoutParams['public_img']?>ilustradores/yolanda.png" style="    width: 250px;"  />
                    <div class="nombre">
                        <strong>Yolanda Cabrera</strong>

                    </div>
                    <div class="puesto">
                        <small>Ilustradora</small>
                    </div>

                    <div class="bop mt-20">
                        <a href="<?=MENU_URL?>nosotros/equipo"  class="btn-outline-blue">VER BIOGRAFÍA</a>
                    </div>
                </div>
            </div>


            <div class="col-sm-4">
                <div class="ilustrador">
                    <img src="<?= $_layoutParams['public_img']?>ilustradores/carolina.png" style="    width: 250px;"  />
                    <div class="nombre">
                        <strong >Carolina Valtuille</strong>

                    </div>
                    <div class="puesto">
                        <small>Ilustración infantil y juvenil</small>
                    </div>

                    <div class="bop  mt-20">
                        <a href="<?=MENU_URL?>nosotros/equipo"   class="btn-outline-blue">VER BIOGRAFÍA</a>
                    </div>
                </div>
            </div>


    </div>
    </div>
</section>



<section style="background: #f2f2f2;  padding-top:30px; padding-bottom:260px; margin-bottom:-160px;" class="section home-section" >
    <div clasS="container">
        <div class="text-center " stye="margin-top:40px;">
            <h2 class="sub-title" style="font-family:'Gloria Hallelujah';color:#29abe2; ">Somos solidarios</h2>
        </div>

        <div clasS="row">
            <div clasS="col-sm-3  text-center">

                <img src="<?= $_layoutParams['public_img']?>nosotros/embajadores-insignia.png"  style="margin-top:10px;max-height:160px;"/>
            </div>
            <div clasS="col-sm-6 text-center">

                <p style="margin-top:45px; color:#888; font-size:20px; font-family: 'Gloria Hallelujah'; line-height: 2em;">
                    Un porcentaje de los beneficios netos irán destinados a la Fundación Aladina, la cual ofrece apoyo emocional, psicológico y material a niños y niñas con cáncer.
                </p>
            </div>
            <div clasS="col-sm-3">
                 <img src="http://www.santabeatrizdesilva.com/wp-content/uploads/2015/05/Fundacion-Aladina-tiempoliebre.png" style="margin-top:60px;"/>
            </div>

        </div>
</section>