<div class="book-heading" style="padding:40px 0; background: #29abe2; background-position: center;
    background-size: 100%;
    background-repeat: no-repeat;">
    <div class="overlay"></div>
    <div class=" text-center">
        <h1 class="title-heading" style="color:white">Error 404</h1>
    </div>
</div>
<style>
    .title-heading {
        font-family:"Gloria Hallelujah";
        text-transform: uppercase;
        color:white;
        font-size:50px;
    }
    .mb20 {
        margin-bottom: 20px;
    }

    .overlay {
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
        background: rgba(0, 0, 0, .3);
    }

    .contact ul li a {
        padding: 10px;
        display: block;
        color: #29abe2;
    }

    .social-contact {
        list-style: none
    }

    .social-contact li {
        border-bottom: 0px !important;
        list-style: none;
        display: inline-block;
        margin: 2px 5px;
    }

    .social-contact li a {
        text-decoration: none !important;
        border: 1px dashed #29abe2;
        height: 40px;
        width: 40px;
        text-align: center;
        line-height: 1.3em;
        color: #29abe2;
        font-size: 16px;
        border-radius: 100%;
    }

    .social-contact li a:hover {
        color: #333;
    } .team-member {font-family: 'Gloria Hallelujah'; color:#29abe2; text-align:left; line-height:1em; font-size:43Px;}
    .nombre {font-family: 'Gloria Hallelujah'; color:#29abe2; text-align:center; font-size:43Px;}
    .team-member .nombre{line-height:1em; margin-top:30px; text-align:left;}

    .puesto {

        font-family:"Gloria Hallelujah"; font-size:20px; color:#333;}
    .descripcion {margin-top: 20px;}

    .team-member {margin-bottom:40px;}

    .bop {margin-top:5px; font-family:"Gloria Hallelujah";}

</style>
<div class="blocks-container style-2">

	<!-- BLOCK "TYPE 10 STYLE 2 PAGE 1.2" -->
	<div  style="margin: 150px 0;">
	<div class="block block-type-10">


	   <div class="row">
				<div class="col-xs-12">
                        <div class="error-content section-title text-center">


                            <p>La página que buscas no existe o no está disponible.</p>
                            <br/>
                            <a href="<?=MENU_URL?>" class="btn btn-default">vuelve a la página principal</a>
                        </div>
                    </div>
			</div>


		</div>

	</div>
</div>
