<div class="index-header">
    <hgroup class="article__headline">
        <h2 class="headline__secondary" ><span class="first-letter">Oooops!</h2>
        <h1 class="headline__primary" >¡No tienes permisos!</h1>
    </hgroup>
</div>
<div class="blocks-container style-2">

	<!-- BLOCK "TYPE 10 STYLE 2 PAGE 1.2" -->
	<div  style="margin: 150px 0;">
	<div class="block block-type-10">
	  

	   <div class="row">
				<div class="col-xs-12">
                        <div class="error-content section-title text-center">
							

                            <p>La página a la que intentas acceder no existe o no es accesible.</p>
                            <a href="<?=MENU_URL?>" class="btn btn-default">Volver al inicio</a>
                        </div>    
                    </div>
			</div>
			

		</div>
		
	</div>
</div>
